import type { ArticleSection } from "./types";

/**
 * Antwerpse laag voor kennisbankartikels die Vlaams of Belgisch geframed zijn.
 * De sectie wordt door ArticleTemplate achteraan toegevoegd, vóór de FAQ. Elke
 * laag zegt iets dat alleen in Antwerpen waar is: districtscijfers (AlleCijfers,
 * referentiejaar 2024), stedelijke instrumenten of de manier waarop wij daar werken.
 */
const layers: Record<string, ArticleSection> = {
  "huis-verkopen-antwerpen-gids": {
    heading: "Per district verschilt de verkoop: waar u begint",
    body: "Deze gids beschrijft het verloop voor de hele stad, maar de vraag \"wat brengt mijn huis op en hoe snel\" hangt sterk af van het district.\n\n• **Borgerhout en Berchem** hebben het oudste patrimonium van de stad: ongeveer 45 procent van de woningen dateert van vóór 1946. Vocht, niet-conforme elektriciteit en een laag EPC-label zijn er de regel, niet de uitzondering, en bepalen mee de prijs.\n• **Deurne, Merksem en Wilrijk** zijn naoorlogs: rond 40 procent van de woningen werd gebouwd tussen 1946 en 1970. Dat is de generatie gezinswoningen die nu vererft en aan de renovatieplicht botst.\n• **Hoboken en Ekeren** tellen het hoogste aandeel eigenaars (69 procent en meer) en meer eengezinswoningen; verkopen gaan er vaker over een erfenis of een verhuis dan over een investering.\n\nWilt u meteen weten wat voor uw district geldt, kies het dan in het raster onder dit artikel. Voor een concreet bod op een pand in Antwerpen leest u hoe een verkoop bij ons verloopt op de pagina \"Huis verkopen in Antwerpen\".",
  },
  "wat-is-een-vastgoedopkoper": {
    heading: "Huisopkoper of vastgoedopkoper in Antwerpen: wat u mag verwachten",
    body: "In de praktijk zoeken Antwerpenaren vooral op \"huisopkoper Antwerpen\"; het is hetzelfde beroep als wat dit artikel een vastgoedopkoper noemt. Wat een Antwerpse opkoper onderscheidt van een landelijke partij, is districtskennis: weten dat een rijhuis in Deurne-Noord anders gefundeerd is dan een bel-etage in Wilrijk, dat een herenhuis in Zurenborg onder beschermd stadsgezicht kan vallen, en dat de Antwerpse bouwcode bepaalt of een grote eengezinswoning ooit opgesplitst mag worden.\n\nwijkopenpanden.be koopt in alle negen districten van de stad en in de directe rand. Na uw aanvraag nemen wij binnen 2 uur contact op, bezoeken wij het pand binnen 48 uur en ontvangt u dezelfde dag een schriftelijk bod met de berekening erbij. U kiest uw eigen notaris.",
  },
  "verhuren-of-verkopen-antwerpen": {
    heading: "De rekensom verschilt per district",
    body: "Verhuren rendeert het best waar de huurvraag het grootst is en de aankoopprijs het laagst. In Antwerpen is dat een smalle band.\n\n• In **Borgerhout** woont 44 procent van de inwoners in een huurwoning, in **Berchem** 41 procent: de huurmarkt is er diep, maar het patrimonium is oud en de verplichte verbeteringen (isolatie, glas, elektriciteit) drukken het nettorendement.\n• In **Merksem, Hoboken en Ekeren** is twee derde van de bewoners eigenaar; de huurmarkt is er kleiner en een leegstaande gezinswoning verhuurt trager.\n• De Vlaamse regels wegen overal even zwaar: beperkte indexatie voor labels D, E en F sinds 1 oktober 2023, en een aangekondigd minimumlabel D om nog te mogen verhuren vanaf 2030.\n\nWie in Antwerpen een oudere woning met een laag label bezit, staat dus voor de keuze: eerst renoveren en dan verhuren, of nu verkopen in de huidige staat. Wij doen op elk pand in de stad een schriftelijk bod, ook op een verhuurd pand met de huurder erin.",
  },
  "wat-is-mijn-woning-waard-antwerpen": {
    heading: "Richtwaarden per district, en waarom uw straat het verschil maakt",
    body: "De mediaanprijs van een woonhuis lag in het eerste kwartaal van 2026 rond 370.000 euro in de meeste Antwerpse districten en iets hoger in het district Antwerpen zelf (bron: huisprijzen.be). Die mediaan zegt weinig over uw pand: in Borgerhout intramuros en Zurenborg liggen instapklare rijhuizen ver boven dat cijfer, in Deurne-Noord of Antwerpen-Noord ligt een renovatiepand er ver onder.\n\nDrie Antwerpse factoren wegen zwaarder dan elders:\n\n• **Bouwperiode.** Bijna de helft van de woningen in Borgerhout en Berchem dateert van vóór 1946; in Deurne, Merksem en Wilrijk domineert de periode 1946–1970. Het bouwjaar voorspelt de renovatiekost, en die bepaalt het bod van elke koper.\n• **Opsplitsingspotentieel.** De Antwerpse bouwcode beschermt eengezinswoningen tegen opdeling, tenzij één woning van minstens 100 vierkante meter met 15 vierkante meter buitenruimte behouden blijft. Een groot herenhuis dat wél opdeelbaar is, is meer waard voor een investeerder.\n• **Erfgoed.** In Zurenborg, delen van het historisch centrum en langs het Stadspark beperkt een bescherming wat u aan gevel, dak en schrijnwerk mag doen.\n\nEen schriftelijk bod van ons is geen schatting, maar het is wel een concreet cijfer voor uw straat, binnen 48 uur na uw aanvraag.",
  },
  "erfenis-woning-stappenplan": {
    heading: "Een woning erven in Antwerpen: wat er lokaal bijkomt",
    body: "Het stappenplan hierboven geldt in heel Vlaanderen. In Antwerpen komen er drie lokale gegevens bij.\n\n• **Leegstand kost hier geld.** Een woning die twaalf maanden niet als woning wordt gebruikt, kan op het stedelijke leegstandsregister komen; daarna loopt een jaarlijkse leegstandsheffing die elk jaar stijgt. Erfgenamen die nog geen beslissing namen, verliezen zo een jaar én betalen ervoor.\n• **Het typische erfenishuis is naoorlogs.** In Deurne, Merksem en Wilrijk dateert rond 40 procent van de woningen uit 1946–1970; Wilrijk heeft met ongeveer 18,5 procent het hoogste aandeel 65-plussers van de districten. Die woningen hebben doorgaans een laag EPC-label, waardoor een koper na de aankoop onder de renovatieplicht valt en daar in zijn prijs rekening mee houdt.\n• **Erfgenamen wonen zelden allemaal in de stad.** Een verkoop met een volmacht en een notaris naar keuze van elke erfgenaam is bij ons standaard.\n\nHoe een geërfd huis in Antwerpen concreet wordt afgewikkeld, per district, leest u in ons artikel over een geërfd huis verkopen in Antwerpen.",
  },
  "commissie-makelaar-belgie": {
    heading: "Wat dat betekent voor een Antwerps pand",
    body: "Bij een mediaanprijs van rond 370.000 euro voor een woonhuis in de Antwerpse districten (eerste kwartaal 2026) komt een makelaarscommissie van 3 procent plus btw neer op ruwweg 13.000 euro, bovenop de keuringen en de publicatiekosten. Voor een instapklaar pand in een gewilde straat van Berchem of Zurenborg kan een makelaar dat verschil terugverdienen met een hogere prijs. Voor een renovatiepand in Deurne-Noord, Antwerpen-Noord of Borgerhout is de kopersgroep smal en weegt de commissie zwaarder op de netto-opbrengst.\n\nwijkopenpanden.be rekent geen commissie en betaalt de keuringen en de ontruiming. U krijgt binnen 48 uur na uw aanvraag een schriftelijk bod; reken beide scenario's netto door voor u kiest.",
  },
  "keuringen-bij-verkoop-woning": {
    heading: "Keuringen in Antwerpen: wat wij van u overnemen",
    body: "De keuringen in dit artikel zijn Vlaams, maar in Antwerpen zijn ze zelden een formaliteit. Bijna de helft van de woningen in Borgerhout en Berchem dateert van vóór 1946: een niet-conforme elektriciteitskeuring en een positief asbestattest zijn er eerder regel dan uitzondering. In appartementsgebouwen op de Linkeroever en in Deurne uit de jaren 1960–1980 komt daar het asbestattest van de gemene delen bij, dat via de syndicus loopt.\n\nVerkoopt u aan wijkopenpanden.be, dan laat u geen keuring uitvoeren: wij bestellen EPC, elektriciteitskeuring en asbestattest zelf na de aankoop en trekken die kost niet van het bod af. Keuringen bestellen kan trouwens ook zonder te verkopen, via onze zusteronderneming Berabrick in de Jezusstraat.",
  },
  "pand-in-slechte-staat-verkopen": {
    heading: "Waar de slechte staat in Antwerpen zit, per district",
    body: "\"Slechte staat\" betekent in elk district iets anders.\n\n• **Antwerpen-Noord, Borgerhout intramuros en het Kiel:** vooroorlogse rijhuizen van vier tot zes meter breed, opstijgend vocht, strokenfunderingen, achteruitbouwen zonder vergunning. De kost zit in structuur en vocht.\n• **Deurne-Noord, Merksem en Wilrijk:** woningen uit 1946–1970 met enkel glas, geen dakisolatie, elektriciteit van vóór 1981 en een stookolietank. De kost zit in energie en installaties.\n• **Linkeroever en Deurne-Zuid:** appartementen in blokken uit de jaren 1960–1980, waar de staat van de gemene delen (lift, gevel, dak) de verkoopbaarheid bepaalt, niet uw eigen unit.\n\nWij bezoeken het pand, benoemen de posten en verrekenen ze in een schriftelijk bod. U hoeft niets te herstellen, op te ruimen of te laten keuren.",
  },
  "huurder-rechten-bij-verkoop-woning": {
    heading: "Verhuurd verkopen in Antwerpen: wat er lokaal speelt",
    body: "In Borgerhout woont 44 procent van de inwoners in een huurwoning, in Berchem 41 procent, in Antwerpen-Noord nog meer. Verhuurde panden zijn er dus courant, en meestal oud: bijna de helft van het patrimonium in Borgerhout en Berchem dateert van vóór 1946. Dat maakt de verkoop van een verhuurd pand in Antwerpen vaak een verkoop van een pand dat aan verbetering toe is, met een huurder erin.\n\nDrie lokale gegevens om mee te nemen:\n\n• De stad Antwerpen verplicht geen conformiteitsattest bij verhuur, behalve na een ongeschikt- of onbewoonbaarverklaring. Vrijwillig aanvragen is gratis als de woning bij de eerste controle in orde is; elke volgende controle kost 210 euro.\n• De Vlaamse indexatiebeperking voor labels D, E en F en het aangekondigde minimumlabel D vanaf 2030 raken vooral de oudere Antwerpse huurpanden.\n• wijkopenpanden.be koopt met de huurder erin, neemt het contract over en organiseert geen bezichtigingen in bewoonde eenheden.\n\nMeer over verhuurd verkopen in Antwerpen, met de districtscijfers, leest u in ons artikel over een verhuurd pand verkopen in Antwerpen.",
  },
  "appartement-vme-syndicus-verkopen": {
    heading: "Appartementen in Antwerpen: waar de VME het verschil maakt",
    body: "Drie kwart van de woningen in Deurne, Berchem en Borgerhout ligt in een meergezinsgebouw; op de Linkeroever domineren de blokken uit de jaren 1960–1980 met grote VME's en actieve syndici. Wat wij bij een Antwerps appartement als eerste opvragen bij de syndicus:\n\n• het reservekapitaal en de laatste twee verslagen van de algemene vergadering;\n• geplande gevel-, dak- of liftwerken, en of er al een beslissing over de kostenverdeling is;\n• het asbestattest van de gemene delen;\n• of de unit een correct busnummer en een vergunde bestemming heeft (in oudere Antwerpse panden is een onvergunde opdeling courant).\n\nU hoeft die documenten niet zelf te verzamelen: wij vragen ze op, en een leeg reservefonds of een geplande gevelrenovatie verwerken wij in ons bod in plaats van ze als reden te gebruiken om af te haken.",
  },
  "opkoper-of-makelaar-verschil": {
    heading: "In Antwerpen: wanneer welk kanaal wint",
    body: "Als vuistregel voor de stad Antwerpen:\n\n• **Makelaar** bij een instapklaar pand in een gewilde straat: Zurenborg, Oud-Berchem, het Zuid, de Stationsbuurt in Berchem, Deurne-Centrum rond het Boekenbergpark. Daar zijn de kopers talrijk en verdient de commissie zichzelf terug.\n• **Opkoper** bij een renovatiepand in Antwerpen-Noord, Borgerhout, Deurne-Noord of het Kiel, bij een verhuurd pand, bij een erfenis met meerdere erfgenamen of bij een scheiding die snel moet. Daar is de kopersgroep smal, springen financieringen af en weegt de commissie op een lagere prijs.\n\nwijkopenpanden.be is een Antwerpse huisopkoper: contact binnen 2 uur, bezoek binnen 48 uur, schriftelijk bod dezelfde dag, en een eerlijk advies als u met een makelaar beter af bent.",
  },
  "betrouwbaar-verkopen-aan-opkoper": {
    heading: "Een Antwerpse opkoper toetsen",
    body: "Wie \"huisopkoper Antwerpen\" zoekt, vindt een handvol partijen met vergelijkbare beloftes: bod binnen 24 uur, voorschot tot 25.000 euro, geen kosten. Toets ze op wat er achter zit:\n\n• Wie staat er als koper op de akte, en is dat dezelfde partij als degene die het bod deed?\n• Koopt de partij met eigen middelen, of zoekt ze na uw akkoord nog een investeerder?\n• Welke Antwerpse dossiers kan ze noemen, per district?\n• Wat verandert er aan het bod na het bezoek, en staat dat zwart op wit?\n\nwijkopenpanden.be is een familiebedrijf in de Jezusstraat in Antwerpen, met ondernemingsnummer BE 0797.335.149. Onze zeven controlevragen voor elke opkoper vindt u in het artikel over huisopkopers in Antwerpen.",
  },
  "huis-verkopen-aan-opkoper-verstandig": {
    heading: "Voor welke Antwerpse panden het meestal verstandig is",
    body: "Uit onze dossiers in de stad komen drie profielen terug waar een opkoper netto meestal gelijk of beter uitkomt dan de klassieke markt:\n\n• een vooroorlogs rijhuis in Borgerhout, Antwerpen-Noord of het Kiel met vocht, niet-conforme elektriciteit en een EPC-label E of F;\n• een verhuurd appartement of opbrengstpand in Berchem, Borgerhout of Deurne waar de huurder blijft zitten en de VME werken plant;\n• een naoorlogse gezinswoning in Deurne, Merksem of Wilrijk uit een erfenis met meerdere erfgenamen, leeg en met een stookolietank.\n\nBij een instapklaar pand in Zurenborg, Oud-Berchem of het Zuid zeggen wij u bij het bezoek eerlijk dat de klassieke markt u meer oplevert.",
  },
  "woning-staat-al-maanden-te-koop": {
    heading: "Waarom Antwerpse panden blijven hangen",
    body: "Uit wat wij in de stad zien, zijn dit de drie meest voorkomende oorzaken per district:\n\n• **Antwerpen-Noord, Borgerhout, Kiel:** de vraagprijs is gebaseerd op gerenoveerde buren, terwijl het pand zelf een renovatiebudget van 80.000 tot 150.000 euro vraagt. Kopers met een lening rekenen dat af en haken af.\n• **Linkeroever, Deurne-Zuid:** het appartement is in orde, maar de VME plant een gevel- of liftrenovatie zonder vastgelegde kostenverdeling. Banken en kopers wachten.\n• **Merksem, Wilrijk, Ekeren:** een naoorlogse gezinswoning met label F waar de renovatieplicht na aankoop de koper afschrikt.\n\nStaat uw pand al maanden te koop, dan doen wij binnen 48 uur een schriftelijk bod dat u naast de lopende vraagprijs kunt leggen. Een lopend makelaarscontract hoeft geen belemmering te zijn; lees daarover het artikel over een makelaarscontract opzeggen.",
  },
  "mede-eigendom-verkopen": {
    heading: "Onverdeeldheid in Antwerpen: hoe wij dat aanpakken",
    body: "De meeste geblokkeerde dossiers die wij in Antwerpen zien, zijn erfenissen van een naoorlogse gezinswoning in Deurne, Merksem of Wilrijk met drie of vier erfgenamen, van wie er minstens één buiten de stad of in het buitenland woont. Wat wij doen:\n\n• één schriftelijk bod dat alle mede-eigenaars tegelijk ontvangen, met de berekening erbij, zodat er geen discussie is over wie welk cijfer kreeg;\n• elke mede-eigenaar tekent bij zijn eigen notaris, ook via volmacht vanuit het buitenland;\n• de akte op een datum die voor iedereen past; wij hebben geen financieringsvoorbehoud, dus er valt niemand af.\n\nWeigert één mede-eigenaar, dan lossen wij dat niet op: dat is de weg van de uitonverdeeldheidtreding via de rechtbank. Ons bod kan daar wel als realistisch cijfer dienen.",
  },
};

export function antwerpLayerFor(slug: string): ArticleSection | undefined {
  return layers[slug];
}
