import type { Region } from "./types";

// Cijfers per district: AlleCijfers.be (Statbel), referentiejaar 2024, geraadpleegd september 2026.
const BRON_2024 = "AlleCijfers.be op basis van Statbel, referentiejaar 2024";

export const regions: Region[] = [
  {
    slug: "antwerpen",
    name: "Antwerpen",
    isDistrict: true,
    postcodes: ["2000", "2018", "2020", "2030", "2040", "2050", "2060"],
    metaTitle: "Huis verkopen in Antwerpen: elk district, direct bod",
    metaDescription:
      "Woning verkopen in Antwerpen? wijkopenpanden.be koopt rechtstreeks aan in alle districten van de stad. Contact binnen 2 uur, bezoek binnen 48 uur, geen makelaarskosten.",
    h1: "Woning verkopen in Antwerpen",
    intro:
      "De stad Antwerpen is onze thuismarkt. Wij kopen in alle negen districten: het district Antwerpen zelf (centrum, Zuid, Noord, Kiel, Luchtbal, Linkeroever en de polderdorpen), Deurne, Borgerhout, Berchem, Hoboken, Merksem, Wilrijk, Ekeren en Borsbeek. Elk district heeft zijn eigen pandtypes en zijn eigen gebreken, en dus zijn eigen manier van verkopen. Op deze pagina vindt u de grote lijnen; kies daarna uw district voor de cijfers, de typische verkoopsituaties en onze dossiers daar.",
    marketOverview:
      "De mediaanprijs van een woonhuis lag in het eerste kwartaal van 2026 rond 370.000 euro in de meeste districten en iets hoger in het district Antwerpen zelf (bron: huisprijzen.be). Achter dat cijfer zit een enorme spreiding: instapklare rijhuizen in Zurenborg, Oud-Berchem en het Zuid zitten er ver boven, renovatiepanden in Antwerpen-Noord, Borgerhout intramuros, het Kiel en Deurne-Noord er ver onder. De bouwperiode voorspelt de renovatiekost: bijna de helft van de woningen in Borgerhout en Berchem dateert van vóór 1946, in Deurne, Merksem en Wilrijk domineert de periode 1946–1970. Daar komen stedelijke regels bij die een bod mee bepalen: de bouwcode (bescherming van eengezinswoningen tegen opdeling), het beschermd stadsgezicht in Zurenborg en delen van het centrum, de luchthavenzone in Deurne-Zuid en het leegstandsregister met zijn jaarlijks stijgende heffing.",
    stats: [
      { label: "Districten", value: "9", note: "Borsbeek sinds 1 januari 2025" },
      { label: "Postcodes stad", value: "2000–2660" },
      { label: "Mediaanprijs woonhuis", value: "± € 370.000", note: "Q1 2026, huisprijzen.be" },
      { label: "Vóór 1946 (Borgerhout)", value: "46%" },
      { label: "1946–1970 (Deurne)", value: "43%" },
      { label: "Huurders (Borgerhout)", value: "44%" },
    ],
    statsSource: `${BRON_2024}; huisprijzen.be Q1 2026`,
    whatWeSee: [
      {
        title: "Het vooroorlogse rijhuis",
        body: "Vier tot zeven meter breed, strokenfundering, opstijgend vocht, elektriciteit van vóór 1981 en vaak een onvergunde achterbouw. Dominant in Borgerhout, Berchem, Antwerpen-Noord en het Kiel.",
      },
      {
        title: "De naoorlogse gezinswoning",
        body: "Rijhuis of bel-etage uit 1946–1970 met enkel glas, geen dakisolatie en een stookolietank. Dominant in Deurne, Merksem, Wilrijk, Hoboken en Ekeren; vererft nu massaal.",
      },
      {
        title: "Het appartement in een oudere VME",
        body: "Blokken uit 1960–1985 op de Linkeroever, in Deurne-Zuid en Berchem-Stationsbuurt. De staat van lift, gevel en dak van het gebouw bepaalt de prijs, niet uw unit.",
      },
      {
        title: "Het herenhuis met erfgoedstatus",
        body: "Zurenborg, Stadspark, Haringrode, delen van het historisch centrum. Hoge waarde, hoge onderhoudsplicht, opsplitsing gebonden aan de bouwcode.",
      },
    ],
    subdistricts: [
      { name: "Centrum, Zuid en Eilandje (2000, 2018)", description: "Appartementen boven handelszaken, herenhuizen aan het Stadspark en in Zurenborg, lofts op het Eilandje. Actiefste huurmarkt van de stad; erfgoedregels courant." },
      { name: "Antwerpen-Noord (2060)", description: "Seefhoek, Stuivenberg, Dam. Hoogste renovatie- en huurdruk; vooroorlogse rijhuizen, stadsvernieuwing." },
      { name: "Kiel en Luchtbal (2020, 2030)", description: "Arbeiderswoningen en sociale hoogbouw naast recente projecten. Toegankelijke prijzen, veel renovatiepanden." },
      { name: "Linkeroever (2050)", description: "Appartementsblokken uit 1960–1980 met grote VME's, en open bebouwing richting de polder." },
      { name: "Berendrecht-Zandvliet-Lillo (2040)", description: "Polderdorpen in het havengebied. Eengezinswoningen met tuin, kleine markt, weinig transacties." },
    ],
    typicalProperties: ["rijhuis", "appartement", "herenhuis", "opbrengsteigendom"],
    pricePerM2: { min: 2000, max: 4500 },
    geo: { lat: 51.2194, lng: 4.4025 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen", "herenhuis-verkopen-antwerpen", "opbrengsteigendom-verkopen-antwerpen"],
    situationLinks: [
      { slug: "huis-verkopen-bij-erfenis", note: "De naoorlogse gezinswoning in Deurne, Merksem of Wilrijk, leeg na een overlijden, met meerdere erfgenamen." },
      { slug: "pand-met-huurders-verkopen", note: "Verhuurde units in Borgerhout, Berchem en Antwerpen-Noord, waar bijna de helft van de bewoners huurt." },
      { slug: "opknappand-verkopen", note: "Vooroorlogse rijhuizen met vocht en niet-conforme elektriciteit, of naoorlogse woningen met label F." },
      { slug: "huis-verkopen-bij-scheiding", note: "Eén neutraal bod voor beide partijen, elk een eigen notaris, akte op een datum die voor beiden werkt." },
    ],
    relatedArticles: ["huis-verkopen-antwerpen-gids", "wat-is-mijn-woning-waard-antwerpen", "huisopkoper-antwerpen-waar-op-letten"],
    recentPurchases: [],
    faqs: [
      {
        question: "Koopt u in elk district van Antwerpen?",
        answer: "Ja, in alle negen: Antwerpen (centrum, Zuid, Noord, Kiel, Luchtbal, Linkeroever, Berendrecht-Zandvliet-Lillo), Deurne, Borgerhout, Berchem, Hoboken, Merksem, Wilrijk, Ekeren en Borsbeek. Ligt uw pand in de directe rand, dan bekijken wij uw aanvraag eveneens.",
      },
      {
        question: "Hoe snel krijg ik een bod op een pand in Antwerpen?",
        answer: "Binnen 2 uur na uw aanvraag nemen wij contact op, binnen 48 uur bezoeken wij het pand en dezelfde dag ontvangt u een schriftelijk bod met de berekening erbij.",
      },
      {
        question: "Welke Antwerpse regels beïnvloeden het bod?",
        answer: "De bouwcode, die eengezinswoningen beschermt tegen opdeling; het beschermd stadsgezicht in Zurenborg en delen van het centrum; de luchthavenzone in Deurne-Zuid; en het leegstandsregister, waar een woning na twaalf maanden leegstand op kan komen met een jaarlijks stijgende heffing. Wij benoemen die elementen in het bod.",
      },
    ],
  },
  {
    slug: "deurne",
    name: "Deurne",
    isDistrict: true,
    postcodes: ["2100"],
    metaTitle: "Huis verkopen in Deurne: direct bod, geen makelaar",
    metaDescription:
      "Woning verkopen in Deurne? wijkopenpanden.be koopt rechtstreeks aan in Deurne-Noord, -Centrum en -Zuid. Contact binnen 2 uur, bezoek binnen 48 uur, geen commissie.",
    h1: "Woning verkopen in Deurne",
    intro:
      "Deurne is met ruim 83.000 inwoners het grootste district van Antwerpen en het district waar de meeste woningen vererven: 43 procent van het patrimonium dateert uit 1946–1970 en 17 procent van de inwoners is 65 of ouder. De markt loopt van dichtbebouwde rijhuizen in Deurne-Noord, aansluitend op Borgerhout, over de Turnhoutsebaan en het Boekenbergpark tot ruimere gezinswoningen en appartementsblokken in Deurne-Zuid, langs de luchthaven. wijkopenpanden.be koopt in alle wijken van Deurne aan, ook de naoorlogse woning met label F en de stookolietank in de tuin.",
    marketOverview:
      "Drie kwart van de Deurnse woningen ligt in een meergezinsgebouw, maar het beeld per wijk verschilt sterk. Rijhuizen in Deurne-Noord zijn toegankelijker geprijsd dan in Berchem of Borgerhout intramuros en tellen meer renovatiepanden. Rond het Boekenbergpark en in Deurne-Zuid halen ruimere halfopen woningen hogere waarden, met de luchthavenzone als beperking voor bijgebouwen en uitbreidingen. De vraag komt van gezinnen die ruimte zoeken op fietsafstand van het centrum; de naoorlogse gezinswoning met enkel glas en een verouderde installatie is precies het type dat op de klassieke markt blijft hangen door de renovatieplicht.",
    stats: [
      { label: "Inwoners", value: "83.471" },
      { label: "Woningen", value: "40.663" },
      { label: "Eigenaars", value: "60%" },
      { label: "In meergezinsgebouw", value: "75%" },
      { label: "Gebouwd 1946–1970", value: "43%" },
      { label: "65-plussers", value: "17%" },
    ],
    statsSource: BRON_2024,
    whatWeSee: [
      { title: "De naoorlogse rijwoning uit een erfenis", body: "Gebouwd tussen 1950 en 1970, enkel glas, geen dakisolatie, elektriciteit van vóór 1981, stookolietank in de kelder of de tuin. Leeg sinds het overlijden, drie erfgenamen, van wie één in het buitenland. Wij verrekenen de renovatiekost en de tanksanering in het bod en regelen de volmachten." },
      { title: "Vocht en niet-conforme elektriciteit in Deurne-Noord", body: "De rijhuizen uit 1900–1940 aansluitend op Borgerhout hebben strokenfunderingen zonder waterkering. Een vochtige kelder en een afgekeurde elektriciteitskeuring zijn hier de norm; wij laten ons er niet door afschrikken." },
      { title: "Appartementen in blokken uit de jaren 1960–1980", body: "In Deurne-Zuid en rond het Rivierenhof liggen appartementsblokken met VME's die aan lift-, gevel- of dakwerken toe zijn. Wij vragen het reservekapitaal en de geplande werken zelf op bij de syndicus en verwerken ze in het bod." },
      { title: "De luchthavenzone", body: "In een deel van Deurne-Zuid gelden geluids- en hoogtebeperkingen voor bijgebouwen en uitbreidingen. Dat drukt de waarde licht, maar maakt een woning niet onverkoopbaar. Wij kennen de zone en prijzen ze correct in." },
    ],
    subdistricts: [
      { name: "Deurne-Noord", description: "Het dichtst bebouwde deel van Deurne, aansluitend op Borgerhout. Rijhuizen uit 1900–1940 domineren. Populair bij gezinnen en investeerders; meer renovatiepanden dan in Deurne-Centrum, prijsniveau vergelijkbaar met Borgerhout extramuros." },
      { name: "Deurne-Centrum en Boekenbergpark", description: "Het hart van Deurne, met de Turnhoutsebaan als commerciële as en het Boekenbergpark en het Rivierenhof als groen. Gemengd aanbod van rijhuizen en appartementen; hogere prijzen dan Deurne-Noord door de voorzieningen." },
      { name: "Deurne-Zuid en luchthavenrand", description: "Ruimer opgezet, meer halfopen en open bebouwing, grotere percelen. Luchthavenbeperkingen voor een deel van de zone, goed inprijsbaar. Aantrekkelijk voor kopers die ruimte zoeken dicht bij de ring." },
    ],
    typicalProperties: ["rijhuis", "halfopen woning", "appartement", "bel-etage"],
    pricePerM2: { min: 1900, max: 3000 },
    geo: { lat: 51.2178, lng: 4.4669 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen", "opbrengsteigendom-verkopen-antwerpen"],
    situationLinks: [
      { slug: "huis-verkopen-bij-erfenis", note: "Het Deurnse erfenishuis: naoorlogs, leeg, met meerdere erfgenamen. Wij regelen volmachten en de akte bij de notaris van elke erfgenaam." },
      { slug: "opknappand-verkopen", note: "Enkel glas, stookolietank, afgekeurde elektriciteit: wij kopen in de huidige staat, zonder herstellingen vooraf." },
      { slug: "huis-verkopen-bij-scheiding", note: "Eén bod voor beide partijen, snel en neutraal; ons Deurnse scheidingsdossier werd in 12 dagen afgerond." },
      { slug: "pand-met-huurders-verkopen", note: "Verhuurde appartementen in Deurne-Centrum: wij nemen het huurcontract over en organiseren geen bezichtigingen." },
    ],
    relatedArticles: ["geerfd-huis-verkopen-antwerpen", "stookolietank-woning-verkopen", "energie-renovatieplicht-vlaanderen-2026", "woning-verkopen-verhuis-woonzorgcentrum"],
    neighbours: ["borgerhout", "merksem", "berchem", "borsbeek", "wommelgem"],
    recentPurchases: [
      { type: "Rijhuis", situation: "Opknapper, eigenaar woonde in woonzorgcentrum", duration: "21 dagen", description: "Rijhuis van 120 vierkante meter in Deurne-Noord. Niet-conforme elektriciteit, vochtige kelder, keuken uit de jaren 1970. Eigenaar in woonzorgcentrum, kinderen beheerden de verkoop. Akte binnen 21 dagen, leegruiming geregeld door wijkopenpanden.be." },
      { type: "Halfopen woning", situation: "Erfenis, twee erfgenamen, woning leeg na overlijden", duration: "28 dagen", description: "Halfopen woning van 175 vierkante meter in Deurne-Centrum, met tuin. Goed onderhouden maar verouderd schrijnwerk. Beide erfgenamen tekenden bij hun eigen notaris. Opbrengst verdeeld na akte." },
      { type: "Appartement", situation: "Scheiding, beide partijen wensten snelle afhandeling", duration: "12 dagen", description: "Instapklaar appartement in Deurne. Beide partijen wilden een snelle en neutrale afhandeling; één bod, elk een eigen notaris." },
      { type: "Appartement", situation: "Investeerder wenste te desinvesteren", duration: "17 dagen", description: "Tweeslaapkamerappartement in Deurne-Centrum, verhuurd. wijkopenpanden.be nam het huurcontract over. Investeerder ontving het nettobedrag na aflossing van het resterende leningssaldo." },
    ],
    faqs: [
      { question: "Wij erven een naoorlogse woning in Deurne met een stookolietank. Moet die eerst gesaneerd worden?", answer: "Neen. Een buitengebruikgestelde of nog actieve stookolietank moet bij verkoop gekeurd of correct buiten gebruik gesteld zijn, maar u hoeft dat niet zelf te laten doen voor u aan ons verkoopt. Wij verrekenen de keuring of de sanering in het bod en regelen ze na de aankoop." },
      { question: "Heeft de nabijheid van de luchthaven invloed op de verkoopprijs in Deurne-Zuid?", answer: "In de zones dichtst bij de luchthaven gelden geluidsbeperkingen en bouwbeperkingen voor bijgebouwen of uitbreidingen. Dat drukt de marktwaarde licht, maar maakt de woning niet onverkoopbaar. Wij kennen de zone en houden er rekening mee in het bod." },
      { question: "Hoe snel kunt u een bod doen op een woning in Deurne?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op, binnen 48 uur bezoeken wij de woning en dezelfde dag ontvangt u een schriftelijk bod. Bij een erfenis met meerdere erfgenamen ontvangt iedereen hetzelfde bod tegelijk." },
    ],
  },
  {
    slug: "borgerhout",
    name: "Borgerhout",
    isDistrict: true,
    postcodes: ["2140"],
    metaTitle: "Huis verkopen in Borgerhout: direct bod, geen makelaar",
    metaDescription:
      "Woning verkopen in Borgerhout? wijkopenpanden.be koopt rechtstreeks aan, ook vooroorlogse rijhuizen met vocht of verhuurde units. Contact binnen 2 uur, bezoek binnen 48 uur.",
    h1: "Woning verkopen in Borgerhout",
    intro:
      "Borgerhout heeft het oudste woningpatrimonium van Antwerpen: 46 procent van de woningen dateert van vóór 1946, en 44 procent van de inwoners huurt. Rijhuizen uit 1880–1930 domineren het straatbeeld intramuros, de prijzen variëren sterk per straat, en de wijk trekt zowel starters als investeerders aan. Dat maakt Borgerhout het district van het verhuurde pand en van de opknapper. wijkopenpanden.be is er actief in elke straat, van de Turnhoutsebaan tot de Zurenborg-rand, en koopt ook panden met vocht, niet-conforme elektriciteit of een huurder erin.",
    marketOverview:
      "Renovatiepanden komen in Borgerhout vaak voor, maar het aandeel instapklare woningen groeit. Oud-Borgerhout, binnen de ring, is gemiddeld duurder dan Borgerhout extramuros door de centrale ligging. De huurmarkt is diep: veel eigenaars kopen als investering, wat de vraag naar instapklare panden opdrijft. Tegelijk botst het oude patrimonium op de Vlaamse huurregels: beperkte indexatie voor labels D, E en F, en een aangekondigd minimumlabel D om nog te mogen verhuren vanaf 2030. Kleine verhuurders met een oud pand verkopen daarom vaker dan vroeger, met de huurder erin.",
    stats: [
      { label: "Inwoners", value: "46.669" },
      { label: "Woningen", value: "23.415" },
      { label: "Huurders", value: "44%" },
      { label: "In meergezinsgebouw", value: "78%" },
      { label: "Gebouwd vóór 1946", value: "46%" },
      { label: "65-plussers", value: "12%" },
    ],
    statsSource: BRON_2024,
    whatWeSee: [
      { title: "Het opgedeelde rijhuis met huurders", body: "Een burgerwoning uit 1900–1930, ooit opgedeeld in twee of drie units, niet altijd vergund, met huurders die al jaren blijven. Wij kopen met de huurders erin, controleren de vergunningstoestand zelf en verrekenen de conformering in het bod." },
      { title: "Vocht en funderingen intramuros", body: "Strokenfunderingen zonder waterkering, opstijgend vocht, vochtige kelders: bij vooroorlogse rijhuizen in Oud-Borgerhout de norm. Geen uitsluitingscriterium, wel een post in de berekening." },
      { title: "Erfgoed aan de Zurenborg-rand", body: "Sommige straten grenzend aan Zurenborg hebben art-deco- of eclectische gevels onder beschermd straatgezicht. Dat verhoogt de waarde en de onderhoudsplicht; wij werken met aannemers die erfgoedervaring hebben." },
      { title: "Elektriciteit van vóór 1981 en asbest", body: "Een afgekeurde elektriciteitskeuring en een positief asbestattest zijn in Borgerhout eerder regel dan uitzondering. Wij regelen de keuringen na de aankoop en trekken die kost niet van het bod af." },
    ],
    subdistricts: [
      { name: "Oud-Borgerhout (intramuros)", description: "Het historische hart binnen de ring. Dichte bebouwing, smalle straten, veel rijhuizen uit 1880–1930. Populair bij jonge kopers die renoveren. Prijsniveau hoger dan extramuros door de centrale ligging." },
      { name: "Borgerhout extramuros", description: "Ruimer opgezet, buiten de ring, richting Deurne. Meer halfopen bebouwing, grotere percelen. Rustiger dan intramuros, goed bereikbaar via de ring. Prijsniveau iets lager, met groeiend potentieel." },
      { name: "Zurenborg-rand", description: "De grens met Zurenborg brengt mee dat sommige Borgerhoutse straten een art-deco of eclectische gevel hebben. Beschermde panden komen hier voor." },
    ],
    typicalProperties: ["rijhuis", "appartement", "opbrengsteigendom"],
    pricePerM2: { min: 1800, max: 3200 },
    geo: { lat: 51.2144, lng: 4.4469 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen", "opbrengsteigendom-verkopen-antwerpen"],
    situationLinks: [
      { slug: "pand-met-huurders-verkopen", note: "Bijna de helft van Borgerhout huurt. Wij nemen het huurcontract over, organiseren geen bezichtigingen en verrekenen een leeg reservefonds of geplande werken." },
      { slug: "opknappand-verkopen", note: "Vooroorlogs rijhuis met vocht, afgekeurde elektriciteit en asbest: wij kopen in de huidige staat." },
      { slug: "huis-verkopen-bij-erfenis", note: "Ons Borgerhoutse erfenisdossier met drie erfgenamen werd in 18 dagen afgerond." },
      { slug: "opbrengsteigendom-verkopen-antwerpen", note: "Twee of drie verhuurde units in één pand: wij rekenen met de reële huurinkomsten en de staat per unit." },
    ],
    relatedArticles: ["verhuurd-pand-verkopen-antwerpen", "verhuurd-pand-verkopen-conformiteitsattest-woningkwaliteit", "ontbrekend-busnummer-onvergund-appartement-antwerpen", "elektriciteitskeuring-niet-conform-verkopen"],
    neighbours: ["deurne", "berchem", "antwerpen-noord", "antwerpen-zuid"],
    recentPurchases: [
      { type: "Rijhuis", situation: "Erfenis, drie erfgenamen, woning leeg", duration: "18 dagen", description: "Rijhuis van 140 vierkante meter in Oud-Borgerhout. Zware renovatie nodig, niet-conforme elektriciteit. Alle drie erfgenamen akkoord na het eerste gesprek. Akte binnen 18 dagen." },
      { type: "Opbrengsteigendom", situation: "Twee verhuurde units, eigenaar wenste te desinvesteren", duration: "24 dagen", description: "Opbrengstpand met twee appartementen, beide verhuurd. Huurrelatie overgenomen. Eigenaar ontving de verkoopprijs netto, zonder makelaarskosten." },
      { type: "Appartement", situation: "Scheiding, beide partijen wensten snelle afhandeling", duration: "14 dagen", description: "Tweeslaapkamerappartement in Borgerhout extramuros. Instapklaar. Akte binnen 14 dagen, beide partijen tekenden bij hun eigen notaris." },
    ],
    faqs: [
      { question: "Mijn rijhuis in Borgerhout is opgedeeld in drie units zonder vergunning. Kan ik verkopen?", answer: "Ja. Een onvergunde opdeling is in Borgerhout courant en geen verkoopsverbod, maar ze moet correct in de akte staan en ze bepaalt mee de waarde: de Antwerpse bouwcode laat een regularisatie niet altijd toe. Wij controleren de vergunningstoestand zelf via het omgevingsloket en verrekenen het risico in het bod. U hoeft niets te regulariseren vóór de verkoop." },
      { question: "Koopt u ook een pand in Borgerhout waar de huurder al jaren zit en weinig betaalt?", answer: "Ja. Een lopend huurcontract gaat bij verkoop van rechtswege over op ons. Een lage huurprijs of een huurder die niet wil meewerken aan bezichtigingen is voor ons geen probleem: wij bezichtigen één keer, met respect voor de huurder, en verrekenen de huurvoorwaarden in het bod." },
      { question: "Zijn er beschermde panden in Borgerhout?", answer: "In de Zurenborg-rand en sommige straten van Oud-Borgerhout zijn er panden met beschermd straatgezicht. Wij werken met erkende aannemers voor erfgoedpanden en kunnen u ook voor dit type een concreet bod doen." },
    ],
  },
  {
    slug: "berchem",
    name: "Berchem",
    isDistrict: true,
    postcodes: ["2600"],
    metaTitle: "Huis verkopen in Berchem: direct bod, geen makelaar",
    metaDescription:
      "Woning verkopen in Berchem? wijkopenpanden.be koopt rijhuizen en appartementen rechtstreeks aan, ook rond het station en in Oud-Berchem. Contact binnen 2 uur, bezoek binnen 48 uur.",
    h1: "Woning verkopen in Berchem",
    intro:
      "Berchem is een van de meest gevraagde districten voor wie net buiten het stadscentrum wil wonen met behoud van een uitstekende bereikbaarheid: station Berchem is een van de drukste van het land, de ring en de A12 liggen op fietsafstand. Dat trekt gezinnen, pendelaars en investeerders aan; 41 procent van de inwoners huurt. Het patrimonium is oud, 45 procent dateert van vóór 1946, en loopt van brede burgerwoningen in Oud-Berchem tot compacte appartementen rond het station en herenhuizen aan de Zurenborg-grens. wijkopenpanden.be koopt in alle wijken van Berchem aan.",
    marketOverview:
      "Rijhuizen in Berchem worden sterk gewaardeerd door de bereikbaarheid en de kwaliteit van de wijk. Appartementen lopen uiteen van studio's rond het station tot grotere eenheden in rustiger straten; drie kwart van de woningen ligt in een meergezinsgebouw. De grens met Zurenborg zorgt in de noordelijke straten voor opwaartse prijsdruk. De huurmarkt is sterk, maar de oude gebouwen botsen op de Vlaamse huurregels rond EPC en indexatie. Voor grote burgerwoningen speelt de Antwerpse bouwcode: opsplitsen kan enkel als één woning van minstens 100 vierkante meter met buitenruimte behouden blijft.",
    stats: [
      { label: "Inwoners", value: "43.811" },
      { label: "Woningen", value: "25.010" },
      { label: "Huurders", value: "41%" },
      { label: "In meergezinsgebouw", value: "75%" },
      { label: "Gebouwd vóór 1946", value: "45%" },
      { label: "65-plussers", value: "14%" },
    ],
    statsSource: BRON_2024,
    whatWeSee: [
      { title: "Het verhuurde appartement rond het station", body: "Compacte units in gebouwen uit 1900–1960, verhuurd aan pendelaars en starters, met een VME die aan gevel- of dakwerken toe is. Wij vragen het reservekapitaal en de geplande werken op bij de syndicus en nemen het huurcontract over." },
      { title: "De brede burgerwoning in Oud-Berchem", body: "Burgerswoningen uit 1900–1930 met hoge plafonds, diepe tuinen en vaak verouderd sanitair en schrijnwerk. Gewild, dus eerlijk advies: instapklaar brengt deze woning op de klassieke markt meer op; met zware renovatie ligt het verschil klein." },
      { title: "Opsplitsing en de bouwcode", body: "Eigenaars van een groot herenhuis rekenen op opsplitsing in appartementen. De Antwerpse bouwcode beschermt eengezinswoningen daartegen, tenzij één woning van minstens 100 vierkante meter met 15 vierkante meter buitenruimte behouden blijft. Wij rekenen het reële potentieel in, niet het gehoopte." },
      { title: "Erfgoed aan de Zurenborg-grens", body: "Straten aan de Berchemse zijde van Zurenborg hebben art-deco- of eclectische gevels die nauwelijks van de beschermde Zurenborg-panden te onderscheiden zijn. Hogere waarde, hogere onderhoudsplicht." },
    ],
    subdistricts: [
      { name: "Berchem-Stationsbuurt", description: "Direct rond station Berchem. Hoge bebouwingsdichtheid, veel appartementen en gemengd gebruik. Sterkste huurmarkt van Berchem; hogere prijzen per vierkante meter, hogere huurinkomsten. Populair bij investeerders." },
      { name: "Oud-Berchem en Driehoekstraat-buurt", description: "Het historische hart, met brede rijhuizen en burgerswoningen uit 1900–1930. Rustige straten, goede scholen en voorzieningen. Hogere waarde dan Deurne bij gelijke staat." },
      { name: "Zurenborg-grens (Berchemse zijde)", description: "De overgang naar Zurenborg. Art-deco en eclectische gevels, beschermd straatgezicht in sommige straten, hoogste prijzen van het district." },
      { name: "Groenenhoek en Nieuw Kwartier", description: "Ruimer opgezet richting Borsbeek en Mortsel: interbellumwoningen, halfopen bebouwing, gezinsmarkt." },
    ],
    typicalProperties: ["rijhuis", "appartement", "burgerwoning", "opbrengsteigendom"],
    pricePerM2: { min: 2200, max: 3500 },
    geo: { lat: 51.1978, lng: 4.4186 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen", "herenhuis-verkopen-antwerpen", "opbrengsteigendom-verkopen-antwerpen"],
    situationLinks: [
      { slug: "pand-met-huurders-verkopen", note: "Verhuurde appartementen in de Stationsbuurt: wij kopen met de huurder erin en vragen de VME-stukken zelf op." },
      { slug: "huis-verkopen-bij-erfenis", note: "Erfgenamen in het buitenland? Ons Berchemse dossier met twee erfgenamen buiten België liep via volmacht in 25 dagen." },
      { slug: "verkopen-zonder-makelaar", note: "Discreet verkopen zonder bord en zonder bezichtigingen, zoals ons dossier in Oud-Berchem in 19 dagen." },
      { slug: "herenhuis-snel-verkopen", note: "Groot herenhuis met een onzeker opsplitsingspotentieel: wij dragen het vergunningsrisico." },
    ],
    relatedArticles: ["verhuurd-pand-verkopen-antwerpen", "appartement-vme-syndicus-verkopen", "beschermd-monument-erfgoedwoning-verkopen", "woning-verkopen-vanuit-buitenland"],
    neighbours: ["antwerpen-zuid", "borgerhout", "deurne", "borsbeek", "mortsel", "wilrijk"],
    recentPurchases: [
      { type: "Rijhuis", situation: "Verkoop zonder makelaar, eigenaar wenste snelle en discrete afhandeling", duration: "19 dagen", description: "Rijhuis van 155 vierkante meter in Oud-Berchem. Goed onderhouden maar verouderd sanitair. Eigenaar wilde geen makelaar en geen bezichtigingen. Akte binnen 19 dagen, eigenaar koos zelf zijn notaris." },
      { type: "Appartement", situation: "Erfenis, twee erfgenamen, discussie over de waarde", duration: "25 dagen", description: "Tweeslaapkamerappartement in de Stationsbuurt. Beide erfgenamen woonden in het buitenland. wijkopenpanden.be regelde het contact met de Belgische notaris. Akte via volmacht ondertekend." },
      { type: "Opbrengsteigendom", situation: "Twee verhuurde units, eigenaar ging met pensioen", duration: "22 dagen", description: "Opbrengstpand met twee appartementen in Berchem-Centrum. Beide units bewoond. wijkopenpanden.be nam de huurrelaties over. Eigenaar ontving de netto verkoopprijs na aflossing van de resterende lening." },
    ],
    faqs: [
      { question: "Is Berchem een district waar ik beter met een makelaar verkoop?", answer: "Voor een instapklaar rijhuis in Oud-Berchem of aan de Zurenborg-grens meestal wel: de kopersgroep is er breed en de commissie verdient zichzelf terug. Voor een verhuurd appartement rond het station, een woning met zware renovatie of een erfenis met erfgenamen in het buitenland ligt het verschil klein en wint de zekerheid. Wij zeggen u bij het bezoek eerlijk welk kanaal voor uw pand het beste is." },
      { question: "Mijn herenhuis in Berchem is 320 vierkante meter. Kan het opgesplitst worden en telt dat mee in uw bod?", answer: "De Antwerpse bouwcode beschermt eengezinswoningen tegen opdeling, tenzij één woning van minstens 100 vierkante meter met een aansluitende buitenruimte van 15 vierkante meter behouden blijft, en enkel als de oorspronkelijke woning meer dan 15 vierkante meter buitenruimte had. Of dat bij uw pand kan, hangt af van de indeling en de tuin. Wij rekenen het reële potentieel in en dragen het vergunningsrisico zelf." },
      { question: "Hoe snel kunt u een bod doen op een pand in Berchem?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op, binnen 48 uur bezoeken wij het pand en dezelfde dag ontvangt u een schriftelijk bod. Bij een appartement vragen wij de VME-informatie op bij de syndicus; die opvraagtermijn bepaalt mee wanneer de akte kan." },
    ],
  },
  {
    slug: "antwerpen-noord",
    name: "Antwerpen-Noord",
    isDistrict: true,
    postcodes: ["2060"],
    metaTitle: "Huis verkopen in Antwerpen-Noord (2060): direct bod",
    metaDescription:
      "Woning verkopen in Antwerpen-Noord, Seefhoek, Stuivenberg of Dam? wijkopenpanden.be koopt rechtstreeks aan, ook panden in renovatiestaat. Contact binnen 2 uur, bezoek binnen 48 uur.",
    h1: "Woning verkopen in Antwerpen-Noord",
    intro:
      "Antwerpen-Noord, postcode 2060, is de zone ten noorden van het stadscentrum met de wijken Seefhoek, Stuivenberg, Dam en de Havenbuurt. Het is het deel van de stad met de hoogste renovatie- en huurdruk: oude arbeiderswijken met rijhuizen van vier tot zes meter breed uit het begin van de twintigste eeuw, naast nieuwe stadsontwikkeling rond Park Spoor Noord en het Eilandje. wijkopenpanden.be koopt in alle straten van Antwerpen-Noord aan, ook panden in grondige renovatiestaat, opgedeelde panden met huurders en panden met een leegstandsdossier.",
    marketOverview:
      "Antwerpen-Noord heeft een breed prijsspectrum. Seefhoek en Stuivenberg trekken investeerders aan die inspelen op de stadsvernieuwing; het aandeel renovatiepanden is hoog, instapklare woningen worden snel opgenomen. Dam is rustiger en ruimer, met meer open en halfopen bebouwing richting het havengebied. De Havenbuurt en de Oude Dokken zijn een nichemarkt van lofts en herontwikkelde pakhuizen. Wat de verkoop hier bemoeilijkt, is bijna nooit de vraag maar de staat: vocht, structurele gebreken, onvergunde opdelingen en huurders in slecht bezette units. Precies daar is een opkoper die zelf renoveert de logische koper.",
    whatWeSee: [
      { title: "Het smalle arbeidersrijhuis in renovatiestaat", body: "Vier tot zes meter breed, 1900–1930, donkere middenkamer, opstijgend vocht, dak en schrijnwerk aan vervanging toe. Op de klassieke markt haken kopers met een lening af op het renovatiebudget; wij rekenen het in." },
      { title: "Onvergund opgedeelde panden met huurders", body: "Een rijhuis dat ooit in drie of vier units werd opgedeeld zonder vergunning, met huurders en soms zonder correct busnummer. Wij controleren de toestand zelf, kopen met de huurders erin en dragen het regularisatierisico." },
      { title: "Leegstand en de stedelijke heffing", body: "Een pand dat twaalf maanden niet als woning wordt gebruikt, kan op het leegstandsregister komen; de heffing stijgt elk jaar. Wie een leeg pand in Antwerpen-Noord aanhoudt zonder plan, betaalt ervoor. Wij kopen en halen het pand van het register." },
      { title: "Stadsvernieuwing en waardestijging", body: "Rond Park Spoor Noord, het Eilandje en de Oude Dokken stijgen de waarden. Dat weegt mee in ons bod, ook voor een pand dat zelf nog niet gerenoveerd is." },
    ],
    subdistricts: [
      { name: "Seefhoek", description: "Dichtbevolkte arbeiderswijk met rijhuizen uit de vroege twintigste eeuw. Actieve stadsvernieuwing. Veel renovatiepanden, groeiend aanbod instapklare woningen. Populair bij investeerders en starters." },
      { name: "Stuivenberg", description: "Rond het vroegere Stuivenbergziekenhuis, dat wordt herontwikkeld. Rijhuizen en opgedeelde panden, dichte bebouwing, hoge huurdruk." },
      { name: "Dam", description: "Rustigere deelwijk, grenzend aan het havengebied en Park Spoor Noord. Meer open en halfopen bebouwing dan Seefhoek, grotere percelen in sommige straten." },
      { name: "Havenbuurt en Oude Dokken", description: "Gemengd woon-werkgebied in transformatie. Historische pakhuizen naast nieuwbouw. Nichemarkt voor lofts en herbestemde industriële panden." },
    ],
    typicalProperties: ["rijhuis", "opgedeeld pand", "appartement", "opbrengsteigendom"],
    pricePerM2: { min: 1600, max: 2800 },
    geo: { lat: 51.2303, lng: 4.4053 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "opbrengsteigendom-verkopen-antwerpen", "appartement-verkopen-antwerpen"],
    situationLinks: [
      { slug: "opknappand-verkopen", note: "Het smalle rijhuis met vocht en structurele gebreken: wij kopen in de huidige staat, zonder herstellingen vooraf." },
      { slug: "pand-met-huurders-verkopen", note: "Opgedeelde panden met huurders, ook zonder vergunning of busnummer: wij nemen de contracten over." },
      { slug: "opbrengsteigendom-verkopen-antwerpen", note: "Drie of vier units met wisselende bezetting: wij rekenen met de reële inkomsten en de conformeringskost." },
      { slug: "pand-snel-verkopen", note: "Handelspand met woning erboven aan de Handelsstraat of Offerandestraat: wij kopen gemengde panden." },
    ],
    relatedArticles: ["verhuurd-pand-verkopen-antwerpen", "ontbrekend-busnummer-onvergund-appartement-antwerpen", "leegstandsheffing-antwerpen-2026", "ongeschikt-onbewoonbaar-verklaarde-woning-verkopen"],
    neighbours: ["antwerpen-centrum", "borgerhout", "merksem"],
    recentPurchases: [],
    faqs: [
      { question: "Koopt u ook panden in Seefhoek of Stuivenberg die zwaar gerenoveerd moeten worden?", answer: "Ja. Antwerpen-Noord heeft het hoogste aandeel renovatiepanden van de stad en dat is voor wijkopenpanden.be geen uitsluitingscriterium. Wij verrekenen de renovatiekost intern en doen u een eerlijk bod op de huidige staat." },
      { question: "Mijn pand in Antwerpen-Noord staat op het leegstandsregister. Kan ik het nog verkopen?", answer: "Ja. De opname op het register en een eventuele heffing verhinderen de verkoop niet, maar de heffing die al verschuldigd is, blijft voor de eigenaar op het moment van de aanslag. Na de akte vragen wij als nieuwe eigenaar de schrapping aan. Meld het dossier wel vooraf, dan verrekenen wij het correct." },
      { question: "Hoe snel kunt u een bod doen op een pand in Antwerpen-Noord?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op, binnen 48 uur bezoeken wij het pand en dezelfde dag ontvangt u een schriftelijk bod, ook in het weekend." },
    ],
  },
  {
    slug: "antwerpen-centrum",
    name: "Antwerpen-Centrum",
    isDistrict: true,
    postcodes: ["2000"],
    metaTitle: "Woning verkopen in Antwerpen-Centrum: direct bod",
    metaDescription: "Woning verkopen in het centrum van Antwerpen? wijkopenpanden.be koopt appartementen en herenhuizen rechtstreeks aan, ook onder erfgoedregels. Contact binnen 2 uur, bezoek binnen 48 uur.",
    h1: "Woning verkopen in Antwerpen-Centrum",
    intro: "Het stadscentrum van Antwerpen, van de Grote Markt en de Groenplaats over de Meir tot het Eilandje, is de meest gevraagde en meest uiteenlopende vastgoedzone van de stad. Appartementen in historische panden, herenhuizen aan statige lanen, lofts in gerenoveerde pakhuizen op het Eilandje: elke transactie vraagt om een specifieke aanpak. wijkopenpanden.be kent het centrum van binnenuit en koopt rechtstreeks aan, ongeacht het type of de staat.",
    marketOverview: "Het stadscentrum heeft een van de actiefste huurmarkten van Antwerpen. Beleggers kopen compacte appartementen nabij de Meir en het Eilandje voor verhuur aan jonge professionals. Herenhuizen en grotere panden zijn schaars en worden doorgaans snel door projectontwikkelaars of vermogende particulieren opgekocht. Wat de verkoop vertraagt, zijn de erfgoedregels in het historisch centrum, de VME-dossiers van appartementen boven handelszaken en de vergunde bestemming van gemengde panden.",
    whatWeSee: [
      { title: "Het appartement boven een handelszaak", body: "In de winkelstraten rond de Meir en in het historisch centrum liggen woningen boven handelszaken, met een gemengde VME en soms een onduidelijke toegang of bestemming. Wij vragen basisakte en VME-stukken zelf op." },
      { title: "Beschermd straatgezicht", body: "In het historisch centrum gelden strikte regels voor gevelwijzigingen. Verkopen mag altijd; renoveren volgt het advies van Onroerend Erfgoed. Wij kennen de vereisten en werken met erkende aannemers." },
      { title: "Lofts en pakhuizen op het Eilandje", body: "Herontwikkelde industriële panden met bijzondere basisaktes en hoge gemeenschappelijke kosten. Hoge vraag, lage beschikbaarheid." },
    ],
    subdistricts: [
      { name: "Eilandje", description: "Getransformeerde havendokken met moderne nieuwbouw en gerenoveerde pakhuizen. Hoge vraag, lage beschikbaarheid. Populair bij investeerders en jonge professionals." },
      { name: "Historisch centrum (Grote Markt, Groenplaats)", description: "Smalle straten, historische gevels, gemengd residentieel en commercieel gebruik. Appartementen boven winkels zijn courant. Strikte regels voor gevelwijzigingen." },
      { name: "Meir-buurt en Stadspark", description: "Ruimere straten, statige herenhuizen en appartementsgebouwen. Goede bereikbaarheid, nabijheid van het Centraal Station. Hoge bezettingsgraad in de huurmarkt." },
      { name: "Sint-Andries en Universiteitsbuurt", description: "Levendige buurten met rijhuizen, studentenhuisvesting en kleine appartementen. Actieve huurmarkt, veel opgedeelde panden." },
    ],
    typicalProperties: ["appartement", "herenhuis", "opbrengsteigendom", "handelspand met woning"],
    pricePerM2: { min: 2200, max: 4500 },
    geo: { lat: 51.2194, lng: 4.4025 },
    relatedPropertyTypes: ["appartement-verkopen-antwerpen", "herenhuis-verkopen-antwerpen", "opbrengsteigendom-verkopen-antwerpen", "handelspand-snel-verkopen"],
    situationLinks: [
      { slug: "appartement-snel-verkopen", note: "Appartement in mede-eigendom met een gemengde VME: wij regelen het syndicusdossier." },
      { slug: "pand-met-huurders-verkopen", note: "Verhuurde units in de studentenbuurten: wij kopen met de huurders erin." },
      { slug: "herenhuis-snel-verkopen", note: "Herenhuis onder erfgoedregels of met opsplitsingspotentieel: wij dragen het vergunningsrisico." },
    ],
    relatedArticles: ["appartement-vme-syndicus-verkopen", "beschermd-monument-erfgoedwoning-verkopen", "handelspand-gemengd-pand-verkopen-handelshuur"],
    neighbours: ["antwerpen-noord", "antwerpen-zuid", "linkeroever"],
    recentPurchases: [],
    faqs: [
      { question: "Koopt u ook panden in het historische centrum met beschermd straatgezicht?", answer: "Ja. Beschermde gevels of een beschermd straatgezicht vormen geen obstakel. Wij kennen de erfgoedvereisten en werken samen met erkende aannemers die ervaring hebben met historische panden in het centrum." },
      { question: "Hoe snel kunt u een appartement in het centrum aankopen?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op en binnen 48 uur bezoeken wij het pand. Voor appartementen in mede-eigendom vragen wij de VME-informatie op bij de syndicus; de akte kan doorgaans binnen 2 tot 3 maanden worden gepland." },
    ],
  },
  {
    slug: "antwerpen-zuid",
    name: "Antwerpen-Zuid",
    isDistrict: true,
    postcodes: ["2018"],
    metaTitle: "Woning verkopen in Antwerpen-Zuid en Zurenborg: direct bod",
    metaDescription: "Woning verkopen in Antwerpen-Zuid, Zurenborg of Haringrode? wijkopenpanden.be koopt herenhuizen en appartementen aan, ook beschermd erfgoed. Contact binnen 2 uur, bezoek binnen 48 uur.",
    h1: "Woning verkopen in Antwerpen-Zuid",
    intro: "Antwerpen-Zuid, postcode 2018, loopt van het Zuid met het KMSKA over Haringrode en het Stadspark tot Zurenborg aan de grens met Berchem, en behoort tot de meest gewaardeerde woonzones van de stad. De monumentale herenhuizen langs de Cogels-Osylei, de horecabuurt rond het museum en de rustigere straten van het Quartier Latin: elk deel heeft zijn eigen karakter. wijkopenpanden.be koopt in de hele zone aan, ook beschermde panden.",
    marketOverview: "Antwerpen-Zuid heeft een van de sterkste vastgoedmarkten van de stad. Herenhuizen in Zurenborg zijn schaars en worden sterk gewaardeerd, ook door internationale kopers. Appartementen in gerenoveerde panden zijn in trek bij jonge professionals. Eerlijk advies: een instapklaar pand verkoopt hier op de klassieke markt uitstekend. Waar wij het verschil maken, is bij het verwaarloosde herenhuis met erfgoedstatus, het opgesplitste pand met huurders en de erfenis met veel erfgenamen.",
    whatWeSee: [
      { title: "Het beschermde herenhuis met achterstallig onderhoud", body: "Cogels-Osylei, Waterloostraat, Transvaalstraat: beschermd stadsgezicht, leien dak, houten schrijnwerk, EPC zelden boven D. Wij verrekenen de erfgoedgebonden renovatiekost en werken met erkende aannemers." },
      { title: "Het opgesplitste herenhuis rond het museum", body: "Brede panden in de Statiebuurt die ooit in appartementen werden opgesplitst, niet altijd vergund. Wij controleren de toestand en kopen met de huurders erin." },
      { title: "Opsplitsing en de bouwcode", body: "Wie een groot herenhuis wil verkopen aan een ontwikkelaar, botst op de bescherming van eengezinswoningen in de Antwerpse bouwcode. Wij rekenen het reële potentieel in." },
    ],
    subdistricts: [
      { name: "Zurenborg", description: "Iconische wijk met eclectische en art-decobebouwing uit 1895–1914. Cogels-Osylei, Waterloostraat en omgeving zijn beschermd stadsgezicht. Hoogste waarden van Antwerpen-Zuid." },
      { name: "Het Zuid en Statiebuurt", description: "Omgeving van het KMSKA. Breed straatprofiel, ruime herenhuizen, veel opsplitsingen naar appartementen, sterk aanbod van opbrengsteigendommen." },
      { name: "Haringrode en Stadspark", description: "Burgerswoningen uit 1895–1920 rond de Generaal Lemanstraat en het Stadspark. Ruime percelen, erfgoedwaarde." },
      { name: "Quartier Latin", description: "Levendige studentenbuurt met gemengd gebruik. Rijhuizen en appartementen, actieve huurmarkt." },
    ],
    typicalProperties: ["herenhuis", "appartement", "rijhuis", "opbrengsteigendom"],
    pricePerM2: { min: 2400, max: 4200 },
    geo: { lat: 51.2050, lng: 4.4080 },
    relatedPropertyTypes: ["herenhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen", "rijhuis-verkopen-antwerpen"],
    situationLinks: [
      { slug: "herenhuis-snel-verkopen", note: "Beschermd of verwaarloosd herenhuis: wij kopen in de huidige staat en nemen de erfgoedverplichtingen over." },
      { slug: "huis-verkopen-bij-erfenis", note: "Een herenhuis in Zurenborg met vijf erfgenamen: één bod, elk een eigen notaris." },
      { slug: "opbrengsteigendom-verkopen-antwerpen", note: "Opgesplitst pand in de Statiebuurt met huurders: wij nemen de contracten over." },
    ],
    relatedArticles: ["beschermd-monument-erfgoedwoning-verkopen", "oud-gebouw-te-renoveren-pand-verkopen", "renoveren-of-verkopen-oud-pand"],
    neighbours: ["antwerpen-centrum", "berchem", "borgerhout"],
    recentPurchases: [],
    faqs: [
      { question: "Koopt u ook beschermde herenhuizen in Zurenborg aan?", answer: "Ja. wijkopenpanden.be koopt beschermde panden aan en neemt de erfgoedverplichtingen over. Wij kennen de regelgeving rond het beschermd stadsgezicht in Zurenborg en werken met erkende aannemers voor dit type renovaties." },
      { question: "Hoe snel kunt u een herenhuis in Antwerpen-Zuid aankopen?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op en binnen 48 uur bezoeken wij het pand. Voor een herenhuis met erfgoedstatus bezorgen wij u het schriftelijke bod dezelfde dag of de dag erna, na controle van de beschermingsstatus." },
    ],
  },
  {
    slug: "hoboken",
    name: "Hoboken",
    isDistrict: true,
    postcodes: ["2660"],
    metaTitle: "Huis verkopen in Hoboken: direct bod, geen makelaar",
    metaDescription:
      "Woning verkopen in Hoboken? wijkopenpanden.be koopt rechtstreeks aan, van rijhuis in het centrum tot woning aan de Scheldeoever. Contact binnen 2 uur, bezoek binnen 48 uur, geen commissie.",
    h1: "Woning verkopen in Hoboken",
    intro:
      "Hoboken, aan de Schelde ten zuiden van het centrum, is het district van de eigenaar-bewoner: 69 procent van de inwoners woont in een eigen woning en 45 procent van de woningen is een eengezinswoning, meer dan in de andere districten. De bevolking groeide sinds 1990 met ruim een kwart. Het patrimonium combineert een industrieel verleden, de vroegere scheepswerven en de non-ferro-industrie, met rijhuizen uit 1900–1945 in het centrum, naoorlogse gezinswoningen richting Polderstad en recente projecten aan de Scheldeoever. wijkopenpanden.be is actief in alle wijken van Hoboken.",
    marketOverview:
      "Hoboken heeft een toegankelijkere markt dan de centrale districten, wat het aantrekkelijk maakt voor gezinnen en starters. De tram- en fietsverbindingen met het centrum zijn goed. De Schelde en het groen verhogen de leefkwaliteit en de waarden in de betere zones. Omdat de meeste bewoners eigenaar zijn en het aandeel eengezinswoningen hoog is, gaan verkopen hier vaker over een erfenis, een scheiding of een verhuis dan over een investering. Voor oudere panden nabij de vroegere industrie is het bodemattest een aandachtspunt dat wij zelf opvragen.",
    stats: [
      { label: "Inwoners", value: "41.463" },
      { label: "Woningen", value: "18.616" },
      { label: "Eigenaars", value: "69%" },
      { label: "Eengezinswoningen", value: "45%" },
      { label: "Gebouwd vóór 1946", value: "33%" },
      { label: "Bevolkingsgroei sinds 1990", value: "+26%" },
    ],
    statsSource: BRON_2024,
    whatWeSee: [
      { title: "De gezinswoning uit een erfenis of een scheiding", body: "Rijhuis of halfopen woning uit 1930–1970, bewoond door één gezin sinds de bouw, verouderd maar degelijk. Meestal meerdere erfgenamen of twee ex-partners die snel en neutraal willen afronden." },
      { title: "Bodem nabij de vroegere industrie", body: "Rond de vroegere scheepswerven en de non-ferro-industrie vragen kopers en banken naar het bodemattest van OVAM. Wij vragen het zelf op en verrekenen een eventuele saneringsplicht in het bod." },
      { title: "De open woning met zware renovatie", body: "Vrijstaande woningen uit 1950–1975 richting Polderstad en de Scheldeoever, met enkel glas, een stookolietank en een dak dat aan vervanging toe is. Ons Hobokense dossier van dit type werd in 24 dagen afgerond." },
      { title: "Nieuwbouwappartementen aan de Schelde", body: "Recente projecten met Scheldezicht en jonge VME's. Instapklaar verkoopt hier op de klassieke markt vlot; wij zeggen u dat eerlijk bij het bezoek." },
    ],
    subdistricts: [
      { name: "Hoboken-Centrum", description: "Het commerciële hart van Hoboken, met de Kioskplaats en de Berkenrodelei. Gemengd aanbod van rijhuizen uit 1900–1945 en appartementen. Goede voorzieningen en tram." },
      { name: "Scheldeoever en Polderstad", description: "Residentiële zone langs de Schelde met recente projecten en ruimere percelen. Scheldezicht verhoogt de waarde van panden in de eerste rijen; Polderstad is een naoorlogse gezinswijk." },
      { name: "Moretusburg en Hertogvelden", description: "Wijken nabij de vroegere industrie. Rijhuizen en gezinswoningen; bodem en geluid zijn er aandachtspunten die wij inprijzen." },
    ],
    typicalProperties: ["rijhuis", "halfopen woning", "open bebouwing", "appartement"],
    pricePerM2: { min: 1800, max: 2900 },
    geo: { lat: 51.1756, lng: 4.3644 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen", "villa-verkopen-antwerpen"],
    situationLinks: [
      { slug: "huis-verkopen-bij-erfenis", note: "De Hobokense gezinswoning die na een overlijden leegstaat: één bod voor alle erfgenamen, volmachten geregeld." },
      { slug: "huis-verkopen-bij-scheiding", note: "Twee ex-partners, één woning: één neutraal bod, elk een eigen notaris." },
      { slug: "opknappand-verkopen", note: "Open woning met zware renovatie: wij kochten er een in staat van bevinding, akte in 24 dagen." },
      { slug: "blijven-wonen", note: "Verkopen en toch blijven wonen: kapitaal nu, verhuizen wanneer het u past." },
    ],
    relatedArticles: ["geerfd-huis-verkopen-antwerpen", "bodemattest-vlaanderen-verkoop", "stookolietank-woning-verkopen", "huis-verkopen-na-scheiding-antwerpen"],
    neighbours: ["wilrijk", "antwerpen-zuid", "linkeroever"],
    recentPurchases: [
      { type: "Open woning", situation: "Opknapper, zware renovatie, eigenaar wilde niet investeren", duration: "24 dagen", description: "Vrijstaande woning in Hoboken met verouderde installaties en dak. Eigenaar wilde de investering niet meer doen. Wij kochten in staat van bevinding; akte binnen 24 dagen." },
    ],
    faqs: [
      { question: "Mijn woning in Hoboken ligt vlak bij de vroegere industrie. Is het bodemattest een probleem voor de verkoop?", answer: "Meestal niet. Een bodemattest van OVAM is bij elke overdracht in Vlaanderen verplicht; wij vragen het zelf op. Staat het perceel als risicogrond bekend of is er een verontreiniging vastgesteld, dan kan de woning doorgaans toch verkocht worden, met de saneringsplicht correct in het contract. Wij verrekenen dat in het bod in plaats van af te haken." },
      { question: "Wij zijn vier erfgenamen van een gezinswoning in Hoboken. Hoe verloopt dat?", answer: "Alle vier ontvangen tegelijk hetzelfde schriftelijke bod met de berekening. Elke erfgenaam tekent bij zijn eigen notaris, ook via volmacht vanuit het buitenland. Zodra iedereen akkoord is, plannen wij de akte; doorgaans binnen 2 tot 3 maanden, sneller als het dossier eenvoudig is." },
      { question: "Hoe snel kunt u een bod doen op een woning in Hoboken?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op, binnen 48 uur bezoeken wij de woning en dezelfde dag ontvangt u een schriftelijk bod, ook in het weekend en na 18 uur." },
    ],
  },
  {
    slug: "merksem",
    name: "Merksem",
    isDistrict: true,
    postcodes: ["2170"],
    metaTitle: "Huis verkopen in Merksem: direct bod, geen makelaar",
    metaDescription:
      "Woning verkopen in Merksem? wijkopenpanden.be koopt rechtstreeks aan, van naoorlogse gezinswoning tot appartement aan de Bredabaan. Contact binnen 2 uur, bezoek binnen 48 uur, geen commissie.",
    h1: "Woning verkopen in Merksem",
    intro:
      "Merksem, in het noorden van de stad tussen Ekeren, Deurne en het Albertkanaal, is het district van de naoorlogse gezinswoning: 41 procent van de woningen werd gebouwd tussen 1946 en 1970 en 67 procent van de inwoners is eigenaar. Rijhuizen en halfopen woningen uit die periode domineren de rustige woonstraten achter de Bredabaan; de kanaalzone en de haven geven het district een industrieel reliëf. wijkopenpanden.be koopt in alle wijken van Merksem aan, ook de woning met label F en de stookolietank in de tuin.",
    marketOverview:
      "Merksem heeft een stabiele lokale markt, gedragen door gezinnen. De prijzen liggen lager dan in de centrale districten, wat het een instappunt maakt voor kopers die ruimte zoeken. De tram over de Bredabaan en de ring verbinden het district vlot met het centrum. Het typische verkoopdossier is de naoorlogse woning die vererft: enkel glas, geen dakisolatie, elektriciteit van vóór 1981, vaak een stookolietank. Op de klassieke markt blijft dat type hangen door de renovatieplicht die de koper na aankoop treft; wij kopen het in de huidige staat.",
    stats: [
      { label: "Inwoners", value: "46.356" },
      { label: "Woningen", value: "21.883" },
      { label: "Eigenaars", value: "67%" },
      { label: "Eengezinswoningen", value: "35%" },
      { label: "Gebouwd 1946–1970", value: "41%" },
      { label: "65-plussers", value: "10%" },
    ],
    statsSource: BRON_2024,
    whatWeSee: [
      { title: "De naoorlogse gezinswoning uit een erfenis", body: "Rijhuis of halfopen woning uit 1950–1970, decennialang bewoond door hetzelfde gezin, met de originele keuken, enkel glas en een stookolietank. Leeg na een overlijden of een verhuis naar het woonzorgcentrum." },
      { title: "Verkopen en blijven wonen", body: "Oudere eigenaars in Merksem willen het kapitaal uit hun woning halen zonder te verhuizen. Ons Merksemse dossier van dit type liep in 21 dagen: verkoop, huurcontract en kapitaal beschikbaar." },
      { title: "Appartementen langs de Bredabaan", body: "Gebouwen uit 1960–1990 met kleine VME's en verouderde liften of gevels. Wij vragen het reservekapitaal en de geplande werken op bij de syndicus." },
      { title: "De kanaalzone", body: "Woningen nabij het Albertkanaal en de haveninfrastructuur, met een gemengd karakter. Wij beoordelen elk pand op zijn eigen merites; ook hier kopen wij aan." },
    ],
    subdistricts: [
      { name: "Merksem-Centrum en Bredabaan", description: "Kern van het district met de Bredabaan als commerciële as en tramlijn. Rijhuizen en appartementen, goede voorzieningen, actieve lokale markt." },
      { name: "Merksem-Heide en Oud-Merksem", description: "Rustige woonstraten met naoorlogse rijhuizen en halfopen woningen, gezinsmarkt, parken zoals het Runcvoortpark." },
      { name: "Kanaalzone en Merksem-Noord", description: "Grenzend aan het Albertkanaal en de haveninfrastructuur. Gemengd residentieel en industrieel karakter, ruimere percelen in sommige straten." },
    ],
    typicalProperties: ["rijhuis", "halfopen woning", "appartement", "bel-etage"],
    pricePerM2: { min: 1700, max: 2700 },
    geo: { lat: 51.2481, lng: 4.4356 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen"],
    situationLinks: [
      { slug: "huis-verkopen-bij-erfenis", note: "De naoorlogse woning die leegstaat na een overlijden: wij kopen in de huidige staat en regelen ontruiming en attesten." },
      { slug: "blijven-wonen", note: "Kapitaal uit uw woning zonder te verhuizen: ons Merksemse dossier werd in 21 dagen afgerond." },
      { slug: "lijfrente-antwerpen", note: "Verkopen met een maandelijkse uitkering en het recht om te blijven wonen." },
      { slug: "opknappand-verkopen", note: "Label F, enkel glas, stookolietank: geen herstellingen vooraf, wij verrekenen alles in het bod." },
    ],
    relatedArticles: ["geerfd-huis-verkopen-antwerpen", "woning-verkopen-verhuis-woonzorgcentrum", "blijven-wonen-na-verkoop", "stookolietank-woning-verkopen"],
    neighbours: ["ekeren", "deurne", "antwerpen-noord"],
    recentPurchases: [
      { type: "Halfopen woning", situation: "Blijven wonen, senioreigenaars", duration: "21 dagen", description: "Halfopen woning in Merksem. Eigenaars verkochten, tekenden gelijktijdig een huurcontract en bleven wonen. Kapitaal beschikbaar na de akte." },
    ],
    faqs: [
      { question: "Onze ouders verhuizen naar een woonzorgcentrum; hun woning in Merksem heeft label F. Verkopen of eerst renoveren?", answer: "Bij een naoorlogse woning met enkel glas, geen dakisolatie en een oude installatie loopt een renovatie tot label D snel op tot enkele tienduizenden euro's, terwijl de meerwaarde op de klassieke markt onzeker is en de koper alsnog onder de renovatieplicht valt. Wij kopen de woning in de huidige staat, benoemen de renovatieposten in het bod en regelen de ontruiming. Reken beide scenario's netto door; wij helpen daarbij." },
      { question: "Kan ik mijn woning in Merksem verkopen en er blijven wonen?", answer: "Ja. U verkoopt en tekent gelijktijdig een huurovereenkomst voor de duur die u kiest, zodat u meteen over het kapitaal beschikt en verhuist wanneer het u past. Ons Merksemse dossier van dit type werd in 21 dagen afgerond." },
      { question: "Koopt u ook woningen in de kanaalzone van Merksem?", answer: "Ja. Ook in de meer industrieel getinte zones van Merksem kopen wij aan. Wij beoordelen elk pand op zijn eigen merites en doen u een eerlijk bod." },
    ],
  },
  {
    slug: "wilrijk",
    name: "Wilrijk",
    isDistrict: true,
    postcodes: ["2610"],
    metaTitle: "Huis verkopen in Wilrijk: direct bod, geen makelaar",
    metaDescription:
      "Woning verkopen in Wilrijk? wijkopenpanden.be koopt rechtstreeks aan, van bel-etage en gezinswoning tot appartement aan de Bist. Contact binnen 2 uur, bezoek binnen 48 uur, geen commissie.",
    h1: "Woning verkopen in Wilrijk",
    intro:
      "Wilrijk, ten zuiden van het centrum rond de Bist en de campus van de universiteit, heeft het hoogste aandeel 65-plussers van alle Antwerpse districten: ongeveer 18,5 procent. Twee derde van de inwoners is eigenaar en 40 procent van de woningen werd gebouwd tussen 1946 en 1970. Dat is de generatie bel-etagewoningen en halfopen gezinswoningen die nu vererft of vrijkomt bij een verhuis naar een woonzorgcentrum. wijkopenpanden.be koopt in alle wijken van Wilrijk aan, van de Bist tot Valaar, Elsdonk en het Neerland.",
    marketOverview:
      "Wilrijk heeft een sterke, stabiele markt met goede bereikbaarheid en ruimere percelen dan de centrale districten. Bel-etagewoningen uit de jaren 1960 met garage beneden en woonruimte boven zijn typisch; ze zijn degelijk gebouwd maar energetisch verouderd en vragen een nieuwe indeling om aan de huidige gezinsvraag te voldoen. Appartementen concentreren zich rond de Bist en langs de Boomsesteenweg. Rond de campus is er een studentenhuurmarkt. Het typische verkoopdossier is de erfenis of de verhuis van een oudere eigenaar, waarbij de kinderen de verkoop beheren en zekerheid en snelheid belangrijker zijn dan de laatste procent.",
    stats: [
      { label: "Inwoners", value: "42.463" },
      { label: "Woningen", value: "21.433" },
      { label: "Eigenaars", value: "64%" },
      { label: "Eengezinswoningen", value: "36%" },
      { label: "Gebouwd 1946–1970", value: "40%" },
      { label: "65-plussers", value: "18,5%" },
    ],
    statsSource: BRON_2024,
    whatWeSee: [
      { title: "De bel-etage uit de jaren 1960", body: "Garage en berging beneden, leefruimte op de verdieping, enkel glas, geen dakisolatie, stookolie of een oude gasketel. Degelijk gebouwd, maar de indeling en het energielabel schrikken kopers met een lening af. Wij rekenen de herindeling en de energetische renovatie in." },
      { title: "Verhuis naar het woonzorgcentrum", body: "De kinderen beheren de verkoop, soms met een zorgvolmacht of een bewindvoerder. Wij kennen de procedure, regelen de ontruiming en plannen de akte wanneer de vrederechter of de volmacht het toelaat." },
      { title: "Appartementen rond de Bist", body: "Gebouwen uit 1965–1990 met VME's die aan lift- en gevelwerken toe zijn. Wij vragen het reservekapitaal en de planning op bij de syndicus en verrekenen ze in het bod." },
      { title: "Studentenhuisvesting bij de campus", body: "Opgedeelde woningen en studio's rond de universiteitscampus, met wisselende bezetting. Wij kopen met de huurders erin en controleren de vergunde bestemming." },
    ],
    subdistricts: [
      { name: "Wilrijk-Centrum en de Bist", description: "Het hart van het district rond de Bist, met appartementen, handel en de wekelijkse markt. Goede voorzieningen, tram en bus." },
      { name: "Valaar en Elsdonk", description: "Residentiële wijken met naoorlogse bel-etages, halfopen woningen en ruimere percelen. Gezinsmarkt, rustige straten." },
      { name: "Neerland en Campus", description: "Zone rond de universiteitscampus en het Neerlandpark. Studentenhuisvesting naast gezinswoningen; groen en bereikbaarheid via de Boomsesteenweg." },
    ],
    typicalProperties: ["bel-etage", "halfopen woning", "rijhuis", "appartement"],
    pricePerM2: { min: 2100, max: 3400 },
    geo: { lat: 51.1689, lng: 4.3894 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "appartement-verkopen-antwerpen", "villa-verkopen-antwerpen"],
    situationLinks: [
      { slug: "huis-verkopen-bij-erfenis", note: "De Wilrijkse bel-etage die vererft: één bod voor alle erfgenamen, ontruiming inbegrepen." },
      { slug: "blijven-wonen", note: "Oudere eigenaars die het kapitaal willen zonder te verhuizen: verkoop met huurcontract." },
      { slug: "lijfrente-antwerpen", note: "Een maandelijkse uitkering bovenop het pensioen, met het recht om te blijven wonen." },
      { slug: "opknappand-verkopen", note: "Label F en een verouderde indeling: wij kopen in de huidige staat." },
    ],
    relatedArticles: ["geerfd-huis-verkopen-antwerpen", "woning-verkopen-verhuis-woonzorgcentrum", "woning-verkopen-met-zorgvolmacht", "woning-verkopen-onder-bewind"],
    neighbours: ["hoboken", "berchem", "mortsel", "edegem"],
    recentPurchases: [],
    faqs: [
      { question: "Mijn moeder woont in een woonzorgcentrum en ik heb een zorgvolmacht. Mag ik haar woning in Wilrijk verkopen?", answer: "Dat hangt af van wat de zorgvolmacht bepaalt. Staat de verkoop van onroerend goed er uitdrukkelijk in, dan kunt u als lasthebber tekenen; anders is een machtiging van de vrederechter nodig. Wij kennen beide wegen, bezorgen u een schriftelijk bod dat u aan de vrederechter kunt voorleggen en plannen de akte wanneer de machtiging er is." },
      { question: "Is een bel-etage uit de jaren 1960 moeilijk te verkopen in Wilrijk?", answer: "Op de klassieke markt wel: de indeling met de leefruimte boven en het energielabel schrikken jonge gezinnen met een lening af, en de renovatieplicht na aankoop weegt mee. Wij kopen bel-etages in de huidige staat, rekenen de herindeling en de energetische renovatie in en doen u dezelfde dag als het bezoek een schriftelijk bod." },
      { question: "Hoe snel kunt u een bod doen op een woning in Wilrijk?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op, binnen 48 uur bezoeken wij de woning en dezelfde dag ontvangt u een schriftelijk bod met de berekening erbij." },
    ],
  },
  {
    slug: "ekeren",
    name: "Ekeren",
    isDistrict: true,
    postcodes: ["2180"],
    metaTitle: "Huis verkopen in Ekeren: direct bod, geen makelaar",
    metaDescription:
      "Woning verkopen in Ekeren? wijkopenpanden.be koopt rechtstreeks aan, van open bebouwing en villa tot rijhuis in het centrum. Contact binnen 2 uur, bezoek binnen 48 uur, geen commissie.",
    h1: "Woning verkopen in Ekeren",
    intro:
      "Ekeren, in het noorden van Antwerpen, is het meest suburbane district van de stad: 60 procent van de woningen is een eengezinswoning en ruim twee derde van de inwoners is eigenaar. Open en halfopen bebouwing uit 1946–2000 domineert, rond een oude dorpskern met het Hof van Veltwijck en de Sint-Lambertuskerk. wijkopenpanden.be koopt in alle wijken van Ekeren aan, van het centrum tot Donk, Schoonbroek en Mariaburg.",
    marketOverview:
      "Ekeren heeft ruime percelen en een lagere dichtheid dan het centrum, met stabiele prijzen die door gezinnen worden gedragen. De typische verkoop betreft een vrijstaande of halfopen woning uit de jaren 1960–1980 die vererft: degelijk, ruim, maar energetisch verouderd, met een stookolietank en soms een niet-vergund bijgebouw of zwembad. Kopers met een lening rekenen de renovatiekost af; wij kopen in de huidige staat en verrekenen de sloop- of renovatiewaarde.",
    stats: [
      { label: "Inwoners", value: "29.158" },
      { label: "Woningen", value: "13.243" },
      { label: "Eigenaars", value: "69%" },
      { label: "Eengezinswoningen", value: "60%" },
      { label: "Gebouwd 1946–1970", value: "33%" },
      { label: "65-plussers", value: "14%" },
    ],
    statsSource: BRON_2024,
    whatWeSee: [
      { title: "De vrijstaande woning uit de jaren 1960–1980", body: "Ruim perceel, enkel glas, stookolietank, dak aan vervanging toe. Soms meer waard als bouwgrond dan als renovatieobject; wij leggen beide scenario's naast elkaar." },
      { title: "Niet-vergunde bijgebouwen", body: "Tuinhuizen, veranda's, een zwembad zonder vergunning: courant in Ekeren en geen verkoopsverbod. Wij controleren de regularisatiemogelijkheden en verrekenen het risico." },
      { title: "Rijhuizen in de dorpskern", body: "Rond de Kapelsesteenweg en het centrum liggen oudere rijhuizen uit 1900–1945 met de klassieke vocht- en elektriciteitsproblemen." },
    ],
    subdistricts: [
      { name: "Ekeren-Centrum", description: "De oude dorpskern rond de Sint-Lambertuskerk en het Hof van Veltwijck. Rijhuizen, appartementen boven handelszaken, goede voorzieningen." },
      { name: "Donk en Schoonbroek", description: "Residentiële wijken met open en halfopen bebouwing, ruime tuinen, gezinsmarkt. Schoonbroek grenst aan het havengebied." },
      { name: "Mariaburg", description: "Villawijk op de grens met Brasschaat en Kapellen, ruime percelen, oudere villa's uit de jaren 1930–1970." },
    ],
    typicalProperties: ["open bebouwing", "halfopen woning", "villa", "rijhuis"],
    pricePerM2: { min: 1800, max: 2900 },
    geo: { lat: 51.2933, lng: 4.4167 },
    relatedPropertyTypes: ["villa-verkopen-antwerpen", "rijhuis-verkopen-antwerpen", "bouwgrond-verkopen-antwerpen"],
    situationLinks: [
      { slug: "huis-verkopen-bij-erfenis", note: "De ruime gezinswoning die vererft en waar niemand van de erfgenamen wil gaan wonen." },
      { slug: "villa-snel-verkopen", note: "Villa met zware renovatie of sloopwaarde: wij leggen beide scenario's naast elkaar." },
      { slug: "bouwgrond-snel-verkopen", note: "Perceel splitsen of verkopen als bouwgrond: wij dragen het verkavelingsrisico." },
    ],
    relatedArticles: ["geerfd-huis-verkopen-antwerpen", "stookolietank-woning-verkopen", "tuin-of-bouwgrond-apart-verkopen-perceel-splitsen", "pand-verkopen-aan-projectontwikkelaar"],
    neighbours: ["merksem", "brasschaat"],
    recentPurchases: [],
    faqs: [
      { question: "Onze ouderlijke villa in Ekeren is misschien meer waard als bouwgrond. Hoe bepaalt u dat?", answer: "Wij rekenen twee scenario's: renovatie tot een hedendaagse standaard, en sloop met nieuwbouw. De grondwaarde, de bouwvoorschriften van het perceel en de sloop- en asbestkost bepalen welk scenario het hoogste netto bod oplevert. U krijgt beide berekeningen schriftelijk." },
      { question: "Koopt u ook woningen in Ekeren met een niet-vergund bijgebouw of zwembad?", answer: "Ja. Wij controleren of regularisatie mogelijk is via de stad; is dat niet het geval, dan verwerken wij het als risico in het bod. U hoeft niets te slopen voor de verkoop." },
      { question: "Hoe snel kunt u een bod doen op een woning in Ekeren?", answer: "Binnen 2 uur na uw aanvraag nemen wij contact op, binnen 48 uur bezoeken wij de woning en dezelfde dag ontvangt u een schriftelijk bod." },
    ],
  },
  {
    slug: "linkeroever",
    name: "Linkeroever",
    isDistrict: true,
    postcodes: ["2050"],
    metaTitle: "Woning verkopen op Linkeroever (Antwerpen): direct bod",
    metaDescription: "Woning verkopen op de Antwerpse Linkeroever? wijkopenpanden.be koopt appartementen in de blokken en woningen in de groene zones rechtstreeks aan. Contact binnen 2 uur, bezoek binnen 48 uur.",
    h1: "Woning verkopen op de Linkeroever",
    intro: "De Linkeroever, postcode 2050, is het deel van de stad Antwerpen aan de westoever van de Schelde, verbonden met het centrum via de Kennedytunnel, de Waaslandtunnel en de Sint-Annatunnel. De wijk heeft een heel eigen karakter: ruime appartementsblokken uit 1960–1985 langs de oever en rond de Blancefloerlaan, open bebouwing en veel groen richting Sint-Anneke en het Galgenweel. Door de betere prijs-ruimteverhouding trekt de Linkeroever gezinnen en starters aan. wijkopenpanden.be koopt er appartementen én woningen aan.",
    marketOverview: "De Linkeroever heeft een beperkt maar stabiel aanbod. Appartementen in de grote blokken zijn de dominante categorie; de staat van de gemene delen (liften, gevels, platte daken) en het reservekapitaal van de VME bepalen er de prijs meer dan de unit zelf. Open bebouwing in de groene zones is schaars en gewild. De kopersgroep is iets smaller dan op rechteroever; wij kopen ongeacht de marktdiepte, op basis van de lokale waarde en de staat van gebouw en unit.",
    whatWeSee: [
      { title: "Het appartement in een blok uit de jaren 1960–1980", body: "Ruim, soms met Scheldezicht, maar in een gebouw dat aan gevel-, dak- of liftrenovatie toe is, met een VME die de kostenverdeling nog moet beslissen. Wij vragen de stukken zelf op bij de syndicus en verrekenen de geplande werken." },
      { title: "Het asbestattest van de gemene delen", body: "In gebouwen van vóór 2001 is een asbestattest verplicht bij verkoop, ook voor de gemene delen via de syndicus. Wij regelen dat na de aankoop." },
      { title: "Open bebouwing in de groene zones", body: "Woningen uit 1960–1990 op ruime percelen richting Sint-Anneke, met stookolietank en verouderde installaties. Schaars en gewild; instapklaar verkoopt op de klassieke markt vlot." },
    ],
    subdistricts: [
      { name: "Oever en Blancefloerlaan (de blokken)", description: "Grote appartementsblokken uit 1960–1985 langs de Scheldeoever en de Blancefloerlaan. Ruime appartementen, actieve syndici, stabiele huurmarkt." },
      { name: "Sint-Anneke en Galgenweel", description: "Groener en lager, met open en halfopen bebouwing, het strand van Sint-Anneke en het Galgenweel. Populariteit groeit door de prijs-ruimteverhouding." },
    ],
    typicalProperties: ["appartement", "open bebouwing", "halfopen woning"],
    pricePerM2: { min: 1700, max: 2800 },
    geo: { lat: 51.2183, lng: 4.3764 },
    relatedPropertyTypes: ["appartement-verkopen-antwerpen", "villa-verkopen-antwerpen"],
    situationLinks: [
      { slug: "appartement-snel-verkopen", note: "Appartement in een blok met grote werken op komst: wij verrekenen de VME-planning in plaats van af te haken." },
      { slug: "huis-verkopen-bij-erfenis", note: "Geërfd appartement met Scheldezicht en een leeg reservefonds: één bod voor alle erfgenamen." },
      { slug: "pand-met-huurders-verkopen", note: "Verhuurde units in de blokken: wij nemen het huurcontract over." },
    ],
    relatedArticles: ["appartement-vme-syndicus-verkopen", "asbestattest-bij-verkoop-woning", "keuringen-bij-verkoop-woning"],
    neighbours: ["antwerpen-centrum", "hoboken"],
    recentPurchases: [],
    faqs: [
      { question: "Koopt u ook appartementen in de grote blokken op de Linkeroever?", answer: "Ja. wijkopenpanden.be koopt appartementen in appartementsblokken aan, ook als de VME grote werken plant of het reservekapitaal laag is. Wij vragen de VME-informatie zelf op bij de syndicus en verrekenen de staat van de gemene delen in ons bod." },
      { question: "Is de Linkeroever moeilijker te verkopen dan rechteroever?", answer: "De doelgroep is iets smaller dan in de centrale districten, maar wijkopenpanden.be koopt ongeacht de marktdiepte. Wij doen u een bod op basis van de lokale marktwaarde en de staat van gebouw en unit, binnen 48 uur na uw aanvraag." },
    ],
  },
  {
    slug: "borsbeek",
    name: "Borsbeek",
    isDistrict: true,
    postcodes: ["2150"],
    metaTitle: "Huis verkopen in Borsbeek: direct bod, geen makelaar",
    metaDescription: "Woning verkopen in Borsbeek, sinds 2025 district van Antwerpen? wijkopenpanden.be koopt rechtstreeks aan. Contact binnen 2 uur, bezoek binnen 48 uur, geen commissie.",
    h1: "Woning verkopen in Borsbeek",
    intro: "Borsbeek is sinds 1 januari 2025 het negende district van Antwerpen, na de fusie met de stad. Het is klein maar heeft een eigen markt met rijhuizen, halfopen en open bebouwing, ingebed tussen Berchem, Deurne en Mortsel, vlak bij de ring en station Berchem. Dat maakt Borsbeek aantrekkelijk voor pendelaars en gezinnen die stadscomfort en rustig wonen willen combineren. wijkopenpanden.be koopt in alle straten van Borsbeek aan.",
    marketOverview: "Borsbeek heeft een stabiele markt, gedragen door gezinnen. De schaal zorgt voor een beperkt aanbod, wat de waarden stabiel houdt; woningen wisselen er minder vaak van eigenaar dan in de grotere districten. Het typische dossier is de interbellum- of naoorlogse gezinswoning die vererft, met de gebruikelijke energetische achterstand. De fusie met Antwerpen brengt de stedelijke reglementen mee, waaronder de bouwcode en het leegstandsregister.",
    subdistricts: [],
    typicalProperties: ["rijhuis", "halfopen woning", "open bebouwing"],
    pricePerM2: { min: 2100, max: 3200 },
    geo: { lat: 51.1978, lng: 4.4736 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen"],
    situationLinks: [
      { slug: "huis-verkopen-bij-erfenis", note: "De gezinswoning die vererft: één bod voor alle erfgenamen." },
      { slug: "opknappand-verkopen", note: "Renovatiepanden zijn geen obstakel: wij verrekenen de renovatiekost." },
    ],
    neighbours: ["berchem", "deurne", "mortsel", "wommelgem"],
    recentPurchases: [],
    faqs: [
      { question: "Is Borsbeek nu een district van Antwerpen, en verandert dat iets voor de verkoop?", answer: "Ja, sinds 1 januari 2025. Voor de verkoop zelf verandert er weinig, maar de stedelijke reglementen van Antwerpen gelden voortaan ook in Borsbeek, waaronder de bouwcode en het leegstandsregister. Wij kennen die regels en verrekenen ze in het bod." },
      { question: "Koopt u ook woningen aan die renovatie nodig hebben in Borsbeek?", answer: "Ja. Renovatiepanden zijn voor wijkopenpanden.be geen obstakel. Wij verrekenen de renovatiekost intern; u hoeft niets te herstellen of te verbouwen voor de verkoop." },
    ],
  },
  {
    slug: "mortsel",
    name: "Mortsel",
    isDistrict: false,
    postcodes: ["2640"],
    metaTitle: "Woning verkopen in Mortsel: direct bod",
    metaDescription: "Woning verkopen in Mortsel? wijkopenpanden.be koopt rechtstreeks aan. Reactie binnen 2 uur, vrijblijvend schriftelijk bod, geen makelaar of commissie.",
    h1: "Woning verkopen in Mortsel",
    intro: "Mortsel grenst aan Berchem en Wilrijk en heeft een eigen vastgoedmarkt met veel gezinswoningen uit het interbellum en de naoorlogse periode, rond de Statielei en het Gemeenteplein. wijkopenpanden.be koopt ook in Mortsel aan.",
    marketOverview: "Rustige residentiële gemeente met stabiele prijzen, goed verbonden met Antwerpen via tram en trein. Het typische dossier is de gezinswoning die vererft.",
    subdistricts: [],
    typicalProperties: ["rijhuis", "halfopen woning"],
    pricePerM2: { min: 2000, max: 3200 },
    geo: { lat: 51.1736, lng: 4.4556 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen"],
    neighbours: ["berchem", "wilrijk", "edegem", "borsbeek"],
    recentPurchases: [],
    faqs: [],
  },
  {
    slug: "edegem",
    name: "Edegem",
    isDistrict: false,
    postcodes: ["2650"],
    metaTitle: "Woning verkopen in Edegem: direct bod",
    metaDescription: "Woning verkopen in Edegem? wijkopenpanden.be koopt rechtstreeks aan. Reactie binnen 2 uur, vrijblijvend schriftelijk bod en geen commissie.",
    h1: "Woning verkopen in Edegem",
    intro: "Edegem is een groene gemeente ten zuiden van Antwerpen, grenzend aan Wilrijk en Mortsel, met voornamelijk open en halfopen bebouwing. wijkopenpanden.be koopt ook in Edegem aan.",
    marketOverview: "Residentiële gemeente met hogere gemiddelde woningprijzen en ruime percelen. Villa's uit de jaren 1960–1980 met een verouderd energielabel zijn er het typische verkoopdossier.",
    subdistricts: [],
    typicalProperties: ["halfopen woning", "open bebouwing", "villa"],
    pricePerM2: { min: 2300, max: 3800 },
    geo: { lat: 51.1533, lng: 4.4428 },
    relatedPropertyTypes: ["villa-verkopen-antwerpen"],
    neighbours: ["wilrijk", "mortsel", "kontich"],
    recentPurchases: [],
    faqs: [],
  },
  {
    slug: "kontich",
    name: "Kontich",
    isDistrict: false,
    postcodes: ["2550"],
    metaTitle: "Woning verkopen in Kontich: direct bod",
    metaDescription: "Woning verkopen in Kontich? wijkopenpanden.be koopt rechtstreeks aan. Eerlijke reactie binnen 2 uur, vrijblijvend schriftelijk bod, geen commissie.",
    h1: "Woning verkopen in Kontich",
    intro: "Kontich is een gemeente ten zuiden van Antwerpen met een rustig woonkarakter en goede verbindingen via de A1 en de trein. wijkopenpanden.be koopt ook in Kontich aan.",
    marketOverview: "Stabiele markt, populair bij gezinnen. Open en halfopen bebouwing uit 1960–1990 domineert.",
    subdistricts: [],
    typicalProperties: ["open bebouwing", "halfopen woning"],
    pricePerM2: { min: 2000, max: 3300 },
    geo: { lat: 51.1333, lng: 4.45 },
    relatedPropertyTypes: ["villa-verkopen-antwerpen"],
    neighbours: ["edegem"],
    recentPurchases: [],
    faqs: [],
  },
  {
    slug: "schilde",
    name: "Schilde",
    isDistrict: false,
    postcodes: ["2970"],
    metaTitle: "Woning verkopen in Schilde: direct bod",
    metaDescription: "Woning verkopen in Schilde of 's-Gravenwezel? wijkopenpanden.be koopt villa's en woningen rechtstreeks aan. Reactie binnen 2 uur en een vrijblijvend schriftelijk bod.",
    h1: "Woning verkopen in Schilde",
    intro: "Schilde, met deelgemeente 's-Gravenwezel, is een groene gemeente ten oosten van Antwerpen, bekend om zijn villabebouwing op ruime percelen. wijkopenpanden.be koopt ook in Schilde aan, ook villa's met zware renovatie of sloopwaarde.",
    marketOverview: "Hogere gemiddelde woningprijzen, veel open bebouwing en villa's uit de jaren 1960–1990. Sloopwaarde versus renovatiewaarde is hier de kernvraag.",
    subdistricts: [],
    typicalProperties: ["villa", "open bebouwing"],
    pricePerM2: { min: 2500, max: 4500 },
    geo: { lat: 51.2667, lng: 4.5833 },
    relatedPropertyTypes: ["villa-verkopen-antwerpen"],
    neighbours: ["wommelgem", "brasschaat"],
    recentPurchases: [],
    faqs: [],
  },
  {
    slug: "brasschaat",
    name: "Brasschaat",
    isDistrict: false,
    postcodes: ["2930"],
    metaTitle: "Woning verkopen in Brasschaat: direct bod",
    metaDescription: "Woning verkopen in Brasschaat? wijkopenpanden.be koopt aan. Eerlijk contact binnen 2 uur, geen makelaarskosten.",
    h1: "Woning verkopen in Brasschaat",
    intro: "Brasschaat, ten noorden van Ekeren, is een van de welvarendste gemeenten van de regio, met een sterk aanbod van ruime villa's en halfopen woningen. wijkopenpanden.be koopt ook in Brasschaat aan.",
    marketOverview: "Stabiele markt met hogere gemiddelde woningwaarden, veel groen en ruime percelen. Oudere villa's met een laag energielabel en niet-vergunde bijgebouwen zijn het typische dossier.",
    subdistricts: [],
    typicalProperties: ["villa", "halfopen woning", "open bebouwing"],
    pricePerM2: { min: 2800, max: 5000 },
    geo: { lat: 51.2978, lng: 4.4944 },
    relatedPropertyTypes: ["villa-verkopen-antwerpen"],
    neighbours: ["ekeren", "schilde"],
    recentPurchases: [],
    faqs: [],
  },
  {
    slug: "wommelgem",
    name: "Wommelgem",
    isDistrict: false,
    postcodes: ["2160"],
    metaTitle: "Woning verkopen in Wommelgem: direct bod",
    metaDescription: "Woning verkopen in Wommelgem? wijkopenpanden.be koopt rechtstreeks aan. Eerlijk contact binnen 2 uur, geen makelaarscommissie.",
    h1: "Woning verkopen in Wommelgem",
    intro: "Wommelgem is een compacte gemeente ten oosten van Antwerpen, grenzend aan Deurne en Borsbeek, met een residentieel karakter: halfopen en open bebouwing en een bescheiden aanbod rijhuizen. De nabijheid van de ring en de E313 maakt Wommelgem aantrekkelijk voor pendelaars. wijkopenpanden.be koopt ook in Wommelgem aan.",
    marketOverview: "Rustige maar stabiele markt. Gezinswoningen met tuin domineren het aanbod; de vraag komt van kopers die de rust van een kleinere gemeente verkiezen met behoud van goede verbindingen.",
    subdistricts: [],
    typicalProperties: ["halfopen woning", "open bebouwing", "rijhuis"],
    pricePerM2: { min: 2000, max: 3100 },
    geo: { lat: 51.2133, lng: 4.51 },
    relatedPropertyTypes: ["rijhuis-verkopen-antwerpen", "villa-verkopen-antwerpen"],
    neighbours: ["deurne", "borsbeek", "schilde"],
    recentPurchases: [],
    faqs: [
      { question: "Koopt u ook woningen in Wommelgem aan?", answer: "Ja. wijkopenpanden.be is actief in Wommelgem en de omliggende gemeenten. Na ontvangst van het adres en een beschrijving van de staat nemen wij binnen 2 uur contact op." },
      { question: "Hoe verschilt de markt in Wommelgem van Antwerpen-stad?", answer: "Wommelgem heeft rustiger straten, ruimere percelen en een meer residentieel profiel dan de Antwerpse districten. De vraag is iets beperkter maar stabieler, gedreven door gezinnen die comfort en bereikbaarheid combineren." },
    ],
  },
];

export function getRegion(slug: string): Region | undefined {
  return regions.find((r) => r.slug === slug);
}
